### ISSUE TITLE
Wiki Reference Guide Menu

### ISSUE THREAD

**Issue by cfGothChic** [framework-one/fw1#12]
love the move to github, but i miss the top level menu on the wiki's reference guide page.  it was helpful to see all the api methods at a glance.  useful for when you want to do something but don't know the right function.

thx, Daria

**Comment by seancorfield** [comment]
This is being addressed in release 3.5 by switching the documentation to `kramdown` instead of `rdiscount` and adding the `{:toc}` class to an list embedded in each page.
