### ISSUE TITLE
Memory issues with rc (request.context) in variables scope

### ISSUE THREAD

**Issue by donners** [framework-one/fw1#159]
Just wanted to query the assignment of rc into the framework's variables scope here:

https://github.com/seancorfield/fw1/blob/54dd08f0b6f12d6af9e8e0266c4f57bed7b9ed84/org/corfield/framework.cfc#L1975

We've been experiencing memory issues and possible race conditions under heavy load and believe it may be related to this.

The rc does not appear to be accessed through the variables scope anywhere, as it is var-scoped at the top of internalView() and internalLayout(), and obviously passed as an argument to all controllers. We've commented out the above line and have not had any issues since.

Would appreciate some input as to what the intention is.

**Comment by Hanzo55** [comment]
@seancorfield is absolutely correct. I cannot recreate whatever test I used to confirm that concurrent incoming threads can modify the REQUEST scope before exiting onRequestStart()...and I suspect I had CFTHREAD on the brain...so I've removed that extraneous incorrect portion of my answer/post.
