### ISSUE TITLE
redirect() with routes?

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#245]
One possibility is to add a `uri` argument that takes precedence over `action`, `path`, and `queryString` and calls `buildCustomURL()` instead of `buildURL()`.

Needs further analysis - hence 3.0 tag, rather than 2.5 - but I may bump it up if 2.5 continues to drag on and I get the analysis completed to my satisfaction.

**Comment by ryanguill** [comment]
So for the most part, redirectCustomURL() works the way I had hoped, and the variables in the path work well too, so thanks for that! But I am having trouble figuring out how to set the baseURL to where it works properly for both fw.redirect and fw.redirectCustomURL.  I thought this would be the appropriate place to put this as it relates to this functionality, but if you would rather me open a new ticket let me know.

Here are the relevant framework configuration settings, please let me know if there is something else that is relevant that I am leaving out.

```
reloadApplicationOnEveryRequest = false,
generateSES = true,
SESOmitIndex = true,
baseURL = 'useCgiScriptName',
```

The application im working with right now is fw1base.local, and is set up in apache with url rewriting rules like this (in case its relevant):

```
<VirtualHost *:80>
    ServerName fw1base.local
    DocumentRoot "E:\home\html\fw1base\www"

	#LogLevel Debug
	ErrorLog "logs/fw1base.local-error.log"
    CustomLog "logs/fw1base.local-access.log" common
    
	ProxyPreserveHost On
	ProxyPassReverse / ajp://localhost:8009/
	
	RewriteEngine On
	
	# dynamic handling of robots.txt:
    RewriteRule ^/robots.txt ajp://localhost:8009/index.cfm/main/robots [P,L]
   
    # handle static assets without rewrite:
    RewriteRule ^.*\.(bmp|BMP|gif|GIF|htc|html?|jpe?g|JPE?G|ico|png|PNG|svg|css|js|wav|mp3|swf|txt|pdf|doc|xls|xml|ttf|woff|eot|otf)$ - [L]
   
    # pass jsp heartbeat request thru directly:
    RewriteRule ^/probe/heartbeat.jsp$ ajp://localhost:8009/probe/heartbeat.jsp [P,L]

    # pass site root request thru directly:
    RewriteRule ^/?$ ajp://localhost:8009/ [P,L]

    # pass test and admin requests thru directly:
    RewriteRule ^/(mxunit|tests|railo-context)/(.*)$ ajp://localhost:8009/$1/$2 [P,L]

    # pass all .cfm / .cfc requests thru:
    RewriteRule ^/(.*\.cf[cm].*)$ ajp://localhost:8009/$1 [P,L]

    # pass all others thru as assumed routes:
    RewriteRule ^/(.*)$ ajp://localhost:8009/index.cfm/$1 [P,L]
	
	<Directory "E:/home/html/fw1base/www">
		Options Indexes FollowSymLinks
		AllowOverride None
		Order allow,deny
		Allow from all
	</Directory>
	
</VirtualHost>
```

With baseURL = 'useCgiScriptName', I get the following:

```
fw.getBaseURL() //=> useCgiScriptName
fw.buildURL(action='main.index') //=> '/' (this looks good)
fw.buildCustomURL(uri='/main/index/') //=> '//main/index/' (note the two leading slashes)
```

So if I use the same for ```fw.redirectCustomURL(uri='/main/index/')```, I get redirected to: ```http://main/index/```, if I use ```fw.redirect(action='main.index')``` I get redirected to ```http://fw1base.local/```

If I change the baseURL framework config to be an empty string, I get this:

```
fw.getBaseURL() //=> '' (empty string)
fw.buildURL(action='main.index') //=> '' (empty string, doing a redirect doesn't work)
fw.buildCustomURL(uri='/main/index/') //=> '/main/index/' (this looks good)
```

so with this setting,  then ```fw.buildCustomURL(uri='/main/index/')``` redirects properly to: ```http://fw1base.local/main/index/``` but ```fw.redirect(action='main.index')``` throws the error: ```invalid url [empty string] for attribute url``` which is an error thrown by the location() function called by fw1 at one.cfc:1022 in the redirect() function.

I've tried some other options, including useRequestURI, but nothing seems to work properly.

I'm sure there is something simple i'm missing.
