### ISSUE TITLE
Create aop1 branch from develop and remove AOP/1

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#299]
Since we're going to drop AOP/1 from the FW/1 bundle for 3.0, we need to create a branch from develop to preserve the current state of the art (and maybe back port it to the AOP/1 repo?), then remove AOP/1 from the develop branch and remove any and all tests and other pieces that depend on it (including updating any documentation in this repo or the main framework-one.github.io repo).

**Comment by seancorfield** [comment]
The main documentation site has also been updated to reflect this removal.

**Comment by cybersonic** [comment]
How come AOP/1 is being removed?

**Comment by seancorfield** [comment]
The original plan was to include AOP/1 with DI/1 in FW/1 3.0, but AOP/1 was too buggy once folks started using it, so it was unbundled (nearly six months ago!). @dbudde is working on a variety of bug fixes in order to get it ready for inclusion in a future FW/1 release at some point.

**Comment by cybersonic** [comment]
Aha, gotcher, I shall have a look at some of the issues. I think it could do with a re-write rather than the existing way of doing things which are very OOP.

**Comment by seancorfield** [comment]
Note that AOP/1 still exists in its own repository as an independent project, but that's the original version from two years ago. The version that was going to be bundled with FW/1 had already been substantially reworked to leverage advances in DI/1 and address a number of bugs that were found early. You can check the FW/1 open issues list for the AOP/1 issues that prevented it being bundled with 3.0 and you can checkout the `aop1` branch in FW/1's repo for the current state of play. If you check the FW/1 closed issue list, you'll see some that were previously addressed - #264 & #277.

As for a "re-write", well, that's sort of what I meant by "substantially reworked" :)

**Comment by cybersonic** [comment]
So should the aop1 branch go to the aop1 repo instead?

**Comment by seancorfield** [comment]
The process (for the last... year or so maybe?) has been to work on DI/1 and AOP/1 etc in the context of FW/1 with the plan being to publish back to the original repo (and fixup the tests so they run independently -- or just remove them from the individual repos).

Both DI/1 and AOP/1 have new tests in the FW/1 repo and a full CI system up on travis-ci.org, which is why development moved there (and you didn't seem to be actively maintaining AOP/1 so I didn't think you'd mind one way or the other).

@dbudde is working off a fork of `fw1`'s `aop1` branch so you probably want to coordinate with him, since he's the most active user of AOP/1 that I know of.

**Comment by dbudde** [comment]
@cybersonic - [As linked to by @seancorfield previously] (https://github.com/framework-one/fw1/commit/0e55663f1b31b98e59dc92137762d237eed464bb#commitcomment-11433972), I am wondering what your ```cleanupArguments()``` does?  I am currently writing up some MXUnit tests designed to test with the method in place and without and see if I get any odd results.  I am having a problem with it in my application and it seems on the surface that the function is unnecessary.  Any insight would be appreciated.

**Comment by cybersonic** [comment]
I *think* since it has been a while, was to actually order the arguments so that they are right compared to the target bean. I need to run it and don't have an example project to do it with at the moment.
