### ISSUE TITLE
Unhandled Paths not working in Railo

### ISSUE THREAD

**Issue by cfsimplicity** [framework-one/fw1#303]
Paths in `framework.unhandledPaths` which include a filename (as opposed to just a directory), are not ignored by FW/1 under the current Railo version (4.2.1). This seems to be because FW/1 converts the path list into a regex pattern and unlike ACF, Railo doesn't want backslashes to be escaped in the third argument of `REReplace()` (the replacement string).

So `/ignoreMe.cfm` is converted into `/ignoreMe\\.cfm` in Railo, instead of `ignoreMe\.cfm` and therefore the filename isn't detected.

The following method would address it:

```
private string function convertUnhandledPathsToRegex( required string unhandledPaths ){
	var escapedPaths = reReplaceNoCase( unhandledPaths, '(\+|\*|\?|\.|\[|\^|\$|\(|\)|\{|\||\\)', '\\\1', 'all' );
	var escapedPathsCorrectedForRailo = replaceNoCase( escapedPaths, '\\', '\', 'all' );
	var pathsAsRegexOr = replaceNoCase( escapedPathsCorrectedForRailo, ',', '|', 'all' );
	return pathsAsRegexOr;
}
unhandledPaths = "/ignoreMe.cfm,/ignoreMe";
result = convertUnhandledPathsToRegex( unhandledPaths );
WriteDump( result IS "/ignoreMe\.cfm|/ignoreMe" );
```
Only invoking it if you've specified unhandled paths would improve performance (very slightly) for those not using them:
```
if ( structKeyExists(variables.framework, 'unhandledPaths') ) {
    variables.framework.unhandledPathRegex = convertUnhandledPathsToRegex( variables.framework.unhandledPaths );
} else {
    variables.framework.unhandledPaths = '/flex2gateway';
    variables.framework.unhandledPathRegex='';
}   
```
Happy to submit a PR if no-one can think of a better solution, but confess I'm a bit baffled by the tests and where one would go.

**Comment by seancorfield** [comment]
I don't think that's really the correct solution (it's certainly a hack). I'll experiment with regex on both ACF and Railo and see what the correct behavior should be. I'll leave this open until I figure it it.

**Comment by seancorfield** [comment]
My concerned with messing with the backslashes is that those are part of the pattern being replaced and so in edge cases you could end up with the wrong result (and the code does the hack for ACF despite the Railo-named variable).

Having experimented on cflive.net, there's definitely a difference in how the backslash is handled between ACF and Railo but it's safer to include a pattern that won't show up in a filename and isn't part of the pattern being manipulated.

I have a solution that I plan to integrate today, based on the direction your code suggests to me. Thank you!

**Comment by cfsimplicity** [comment]
No problem, Sean. I agree my proposal feels hacky, hence the reticence to offer it as a PR. But glad it's at least pointed towards a better solution. Thanks.

**Comment by seancorfield** [comment]
Good idea to move the regex code into the conditional too.
