### ISSUE TITLE
renderData() with custom content type but not serializing data.

### ISSUE THREAD

**Issue by ryanguill** [framework-one/fw1#308]
I have the need to render data that is already serialized to JSON as a content type of application/json.  using ```fw.renderData("json", data)``` will serialize the data again. It seems I do not have the ability to set the content type after the call to ```fw.renderData()``` and setting it before a call to ```fw.renderData("text", data)``` (the only one not to try to transform the data) will override the content type to text/plain.

Could we change the ```renderDataWithContentType()``` function to accept any mimetype as the type and it will not tranform the data, only set the content type? eg: ```fw.renderData("application/json", data)``` ?

If this sounds ok to you I can submit a PR for it.

**Comment by seancorfield** [comment]
I think changing the behavior of `renderData()` like that would be very confusing, but I wouldn't be opposed to adding a variant method, perhaps `renderString()` which takes a content type and a string and does what you want.

At this stage (RC2) I won't include this in 3.0 but would be fine with a PR on `develop` for a 3.1 release.

**Comment by seancorfield** [comment]
Looking at this for 3.1, it seems that the simplest solution would be to add `rawjson` as a supported type for `fw.renderData()` and have it set the content type but not serialize the data to JSON for you.

**Comment by seancorfield** [comment]
Fixed in 3.1 develop branch.
