### ISSUE TITLE
Case Insensitive Routes

### ISSUE THREAD

**Issue by ryanguill** [framework-one/fw1#312]
Discussion here: https://groups.google.com/forum/#!topic/framework-one/vJDb-DQldiY

Research a syntactic way to specify that routes should be case insensitive that also works with resource packs.

**Comment by ryanguill** [comment]
Sean, when you say resource packs do you mean the $RESOURCES stuff in the documentation on this page: http://framework-one.github.io/documentation/developing-applications.html ?

Would you be against just adding a framework setting such as "caseInsensitiveRoutes" that would default to false but if set to true would just do all regular expressions as case insensitive? Or would you only be open to a way to do it in the route definitions themselves to allow the case rules to be specified per route?

In my own needs so far I would only need to either have all routes case sensitive or not, I wouldn't need to be able to specify per route.

Looking around at other frameworks, express is case insensitive by default and provides an application setting to specify case sensitive: http://expressjs.com/api.html#app.route . I can't find anything definitive in coldbox but I believe their routes are case insensitive and I can't tell if you can change that or not. Grails seems to be case sensitive by default and you have to step through quite a few hoops to change that.  Play is also case sensitive but you use regex for your routes anyway

**Comment by seancorfield** [comment]
Re: $RESOURCES -- yes, those are resource packs.

Re: framework setting -- I'm not against that (although I think FW/1 already has too many weird / specific switches).

Re: regex case sensitivity -- in some regex engines you can use `(?i)` to make a regex be case insensitive but I don't know if CFML supports that.

The framework setting would probably be the simplest choice -- I don't know whether that would satisfy everyone's needs here (although you're the first to request this change so maybe you == everyone at this point).

**Comment by ggviana** [comment]
By resources we are talking only about views?
Can you give a example of resource?

**Comment by seancorfield** [comment]
Per Ryan's comment: $RESOURCES -- in the documentation. Nothing to do with views.

**Comment by shawnoden** [comment]
On Wed, Mar 11, 2015 at 9:04 PM, Sean Corfield <notifications@github.com>
wrote:

> Re: regex case sensitivity -- in some regex engines you can use (?i) to
> make a regex be case insensitive but I don't know if CFML supports that.
>

The simple Java String Replace/ReplaceAll() methods use the (?i) syntax for
case insensitivity, and they're accessible from inside ColdFusion. And
they're fast.

It's not really ColdFusion code, but it is available to ColdFusion without
any extra work. And I've always found basic String manipulation like that
to be better with the underlying Java. And did I mention it's fast? :-)

**Comment by seancorfield** [comment]
Fixed in 3.1 develop branch by adding `framework.routesCaseSensitive` which defaults to `true`.
