### ISSUE TITLE
Public vs private methods in one.cfc

### ISSUE THREAD

**Issue by Ronner** [framework-one/fw1#316]
I'm not sure if this is the correct place to raise this point, so forgive me if it's not. I have a question regarding public vs private methods in one.cfc.

In Application.cfc I can override the view() method in order to do anything before or after a view is being rendered. Simply calling super.internalView(argumentcollection=arguments); from the method that overrides view() will do the trick. But the same can not be done with views that FW1 uses based on the current action. Those run through internalView.cfc, which is a private method.

I made internalView in one.cfc public instead of private and did the following in Application.cfc

```cfc
public string function internalView( string viewPath, struct args = { } ) 
{
	local.response = "<p>before #viewPath#</p>";
	local.response &= super.internalView(argumentCollection=arguments);
	local.response &= "<p>after #viewPath#</p>";
	return local.response;
}
```

Seems to work just fine that way, so my question is, would it be an idea to make these kind of methods in FW1 public instead of private so there is more freedom to extend on FW1 yourself?

For me, I am creating an event system that inspects the beans of subsytems if they have any metadata defined (listener definitions), indicating to the event system that they want to be called for certain events. I would like to add onBeforeViewRender and onAfterViewRender events into that event lifecycle, but currently I can only do that for views that are included using the view() method.

Same would go for methods like internalLayout. Or even methods such as getController could be made public so that you can define your own logic if you'd want to.

Any absolute reason as to why these methods are now private and should remain private?

**Comment by seancorfield** [comment]
Read the documentation for what you may and may not override. And questions like this belong on the mailing list.

Anything that is `private` will remain so and is not intended to be used in the way you are attempting.
