### ISSUE TITLE
redirect or hide failure() output based on a config setting

### ISSUE THREAD

**Issue by jcberquist** [framework-one/fw1#320]
It would be nice to have a way to prevent `failure()` from outputting to the screen on a production system. I would like to keep all of the typical `onError()` handling in place (i.e. not override it) because I want that logic followed, but if an error happens there, it would be great to have a way to have only a minimal error output to the screen, while writing more detailed information to disk or the console.

**Comment by seancorfield** [comment]
Then write your own `failure()` method in `Application.cfc`. That's how to extend FW/1.

**Comment by jcberquist** [comment]
Sounds good, the reason I asked is that the docs do say, "You may also consider overriding the failure() method, but that is not documented and not supported.", and it is a private method, so I wasn't sure if it was a good idea to override it.

**Comment by seancorfield** [comment]
There are better ways to suppress the error output -- an error action / view, for example -- but if you have an error in your error handling, `failure()` will still get called so if you _really, really_ want to suppress that output in all cases (in production) then you have no choice but to override it.
