### ISSUE TITLE
Routes - Placeholder variables - end character

### ISSUE THREAD

**Issue by guillaume-boivin** [framework-one/fw1#322]
It would be nice if we could give a list of characters that should be interpreted as ending the placeholder variable in a route.

ex : products/detail/:id/:name.html

Currently this is interpreted as having two placeholder variables (:id and :name.html) when what we want is really just :id and :name.

if I could define / and . as ending the placeholder variable it would work as "expected".

thks

**Comment by seancorfield** [comment]
Placeholder should just be alphanumeric so this is a bug -- `.` should already end a name.

**Comment by guillaume-boivin** [comment]
Seeking advice here as I'm relatively new to the codebase, hence haven't got the big picture. 

The problem comes from here : https://github.com/framework-one/fw1/blob/master/framework/one.cfc#L1755

I would change it to : var placeholders = rematch( '(:[a-zA-Z0-9]+)', routeRegEx.pattern );

Is that ok or I'm missing something here ?

**Comment by seancorfield** [comment]
It still needs the second part of the pattern. I believe it should be:

    var placeholders = rematch( '(:[_a-zA-Z0-9]+)|(\([^\)]+)', routeRegEx.pattern );

That would limit names to alphanumeric (and underscore, which I think is reasonable). The second part is still a placeholder, based on how routes are converted to regex and specifically matches embedded parenthesized patterns.

**Comment by seancorfield** [comment]
My only concern is whether anyone might be relying on `-` being valid in a named placeholder. In which case we'd want `[-_a-zA-Z0-9]` in that first portion.

**Comment by guillaume-boivin** [comment]
Ok, yeah I think that [-_a-zA-Z0-9] would be reasonable. If your ok with it I can send a PR for this.

**Comment by seancorfield** [comment]
Sure. develop branch.

**Comment by seancorfield** [comment]
Fixed by #324
