### ISSUE TITLE
FW1 3.0 issue with injected properties in beans not present when called using DI/1

### ISSUE THREAD

**Issue by sneiland** [framework-one/fw1#327]
In setupApplication() we use the injectProperties method of the bean factory to set some config variables based off logic we only want to be run once on app start, as opposed to using variables.framework.diConfig.
```
getBeanFactory().injectProperties("someService", getSomeConfigAtStartup() );
```
In the controller that calls the service if we try to use the di/1 method for referencing the service like this the injected properties are not set.

```
component accessors="true" {
	property someService;

	function init (fw) {
		variables.fw = arguments.fw;
		return this;
	}

	function default(rc){
		rc.test = variables.someService.someMethod();
	}
}
```

However if we use getDefaultBeanFactory() to get the service bean then they are set.

```
component accessors="true" {

	function init (fw) {
		variables.fw = arguments.fw;
		return this;
	}

	function default(rc){
		rc.test = variables.fw.getDefaultBeanFactory().getBean("someService").someMethod();
	}
}
```

**Comment by seancorfield** [comment]
Can you construct a small, self-contained example that shows this behavior and email it to me? I'm having a hard time imagining the whole code from just the snippets you've posted here. Thanks.

**Comment by sneiland** [comment]
Will do, in the mean time I was reminded to mention that this is happening in a controller being called from an onError request.

**Comment by seancorfield** [comment]
Interesting... That's kind of "out of band" for calling a controller directly. By the time `onError()` kicks in, it's really too late to leverage the framework's request cycle (unless you just mean the automatic invocation of the error action, `main.error` by default?).

**Comment by cfGothChic** [comment]
Yes, it's during the automatic invocation of the error action.

**Comment by seancorfield** [comment]
And where in the request lifecycle is the exception that causes `onError` to be invoked? Is this on ACF9.0.1? Didn't you already run into a problem with error handling on 9.0.1? I'm thinking of https://github.com/framework-one/fw1/issues/319

**Comment by cfGothChic** [comment]
This is on Railo 4.2.  I believe he was referencing an unknown variable in a view.

We did end up downgrading our FW/1 apps to 2.5 on ACF9.0.1 in regards to #319.

**Comment by seancorfield** [comment]
Thanks for the clarification. It always helps to provide as much information about the environment when reporting a bug :)

**Comment by sneiland** [comment]
I've been able to narrow down the bug to services created out of our secondary modules model. Im emailing you a sample app demoing the error.

**Comment by seancorfield** [comment]
Took me a while to figure out what is going on but it isn't a bug :)

Here's what is happening:

Your DI/1 configuration specifies `/model` and `/core/model`. FW/1 uses this for the default bean factory for the top-level application and DI/1 finds both `demo1.cfc` in your `/model` and `demo2.cfc` in your `/core/model`.

As FW/1 initializes each subsystem, it also asks DI/1 to look for _relative_ paths so it uses the configuration to search `/core/model` (which exists) and `/core/core/model` (which does not). It finds `demo2.cfc` and puts it in the subsystem-specific bean factory, which has the default bean factory as the parent. So now you have _two_ `demo2` beans in two different factories.

Your `setupApplication()` modifies the version that exists in the default bean factory. That's what you see when you access `demo2service` via `getDefaultBeanFactory()`. However, the bean factory used to set up `error.cfc`'s dependencies is the _subsystem_ bean factory for `core` in which the `demo2service` alias refers to that local version but `demo1service` refers to the parent factory version.

You've shadowed your bean!

How to fix this...

The idea behind subsystems and bean factories is that each subsystem has its own bean factory with the default bean factory as a parent. That allows each subsystem to see its own beans and those of the default, but not beans in other subsystems.

1. Change the `diLocations` to just `/model`. The default factory with scan `/model` and each subsystem will scan a `model` folder in the subsystem (e.g., `/core/model`).

2. Move the `demo2service` property setup from `setupApplication()` to a new `setupSubsystem()` function that checks the subsystem name passed in and calls `injectProperties()` as needed.

3. In the `error.cfc` controller, use `getBeanFactory()` to get the subsystem's bean factory, not `getDefaultBeanFactory()`.

That's the "correct" idiomatic way to work with bean factories and subsystems.

**Comment by seancorfield** [comment]
If you want to prevent subsystems from having bean factories of their own, and have only a single, default bean factory, you could override `setSubsystemBeanFactory()` and just have it return without doing anything. That won't stop FW/1 from searching subsystem models and creating the bean factory, but it will stop it registering the bean factory and therefore all dependencies will use the parent (default) bean factory.

Not recommended, and not "supported", but it should work.

**Comment by cfGothChic** [comment]
Interesting, I hadn't thought about how 3.0 also changed the behavior of the subsystem factories.  I will have to rethink my current setupSubsystem() design to account for this.  Thanks for the clarification!

**Comment by seancorfield** [comment]
FYI, with the change coming in 3.1 (issue #343) you would be able to disable IoC in specific subsystems by setting `diEngine = 'none'` in the `variables.framework.subsystems` struct (for the named subsystem), e.g.,

    variables.framework = {
        ...
        subsystems = {
            admin = {
                diEngine = "none"
            },
            main = {
                diEngine = "none"
            }
        }
    };

Note that IoC handling happens _before_ `setupSubsystem()` so you can't modify the configuration dynamically!
