### ISSUE TITLE
Could ^ be added to the list delimiters used when checking for an HTTP method in a route regex?

### ISSUE THREAD

**Issue by jcberquist** [framework-one/fw1#330]
Currently line 1735 (on develop) has
```
routeRegEx.method = listFirst( routeRegEx.pattern, '*/' );
```
I would find it helpful to add `^` to this so that a regex that starts with an HTTP method can still use the caret to denote the start of a path. Right now a route of `/test/:id` will match on `/test/5` and `/foo/test/5`. If one wants it to match only `/test/5`, `^` can be added to the route: `^/test/:id`. But this currently won't work if the HTTP method is specified (i.e. `$POST^/test/:id`), since the HTTP method is considered to be specified by the `$` at the start of a route up to the first instance of `*` or `/` (via the above line of code) so `^` ends up as part of the HTTP method and not the path regex.

**Comment by seancorfield** [comment]
Good catch. Please send a PR to the develop branch.
