### ISSUE TITLE
FW/1 3.0 - Header Argument in 'redirect()'

### ISSUE THREAD

**Issue by dbudde** [framework-one/fw1#338]
To aid in certain AJAX request processing, it would be helpful to add a 'header' argument to the 'redirect()' method of the framework.  When the argument is present, the 'redirect()' would no longer call the CF 'location()' method, but would instead create a header with the name being that of the 'header' argument and a value of where the redirect should go.  Once the header is created, then the processing would be aborted using the framework's abort method.

An example here for me was that we are using a form builder system that has an AJAX file upload capability.  Once processing is complete we are able to use a header to tell the form builder where it should move the user to next.

**Comment by seancorfield** [comment]
Implemented and documented for 3.1 (and 3.5).
