### ISSUE TITLE
Add ability to AOP to intercept beans by *type* not just name

### ISSUE THREAD

**Issue by cybersonic** [framework-one/fw1#348]
This might be complicated and go against the run order of AOP1, but it would be great to be able to intercept beans by type (or type hirearchy) so that I can have a common interceptor for a number of beans that extend a common bean.

A use case is where I want to add a security interceptor to all my controllers in fw/1 as well as a logging interceptor that would log all calls to functions.

**Comment by seancorfield** [comment]
Fixed by #350
