### ISSUE TITLE
Is ACF9 support needed?

### ISSUE THREAD

**Issue by nopjmp** [framework-one/fw1#353]
ACF9 was deprecated in December 2014. Is there any reason to support it still since it has stopped getting security patches?

**Comment by nopjmp** [comment]
I see the mistake of my idea while looking at the other open issues and closed issues. There are still older versions of CF in production. Maybe this can happen in a future release. I'll just close this for the time being.

**Comment by seancorfield** [comment]
FWIW, some aspects of FW/1 3.5 will require ACF11 (or Railo 4.1 or later - which really shows the gap between the products).
