### ISSUE TITLE
Subsystems not working: "Unable to find a view for 'main.error' action."

### ISSUE THREAD

**Issue by grantpowell** [framework-one/fw1#354]
Dropped in skeleton code and framework.

Customized necessary parameters to activate subsystems (only edited 2 lines of code).

Moved all files for Views, Model, Controllers and Layouts to the specified subsystem folder.

Loaded application and get the following error:

Exception in onError
The action main.default failed.

Unable to find a view for 'main.error' action.
'/views/main/error.cfm' does not exist. (FW1.viewNotFound)

**Comment by grantpowell** [comment]
Figured it out.

It looks like you also have to specify these parameters in variables.framework (subsystem is "public":

		home = "public" & ':' & "main" & '.' & "default",
		error = "public" & ':' & "main" & '.' & "error", 
		base = "/public",  // must have '/' before subsystem directory name

**Comment by grantpowell** [comment]
Another problem...

This path loads the default view from the default subsystem ("public") instead of from the "admin" subsystem folder:

/Index.cfm?action=admin:main.default

**Comment by seancorfield** [comment]
Please take this to the mailing list since this stuff works just fine for lots of other folks and what you need here is helping debugging your configuration.

**Comment by seancorfield** [comment]
And when you post on the list, remember to provide: the exact version of FW/1 you are using, the contents of your Application.cfc, the version of cfml / which engine, your O/S and version, and detail of your file system structure (path to webroot, location of FW/1 files, location of skeleton app, any relevant mappings and so on).

**Comment by grantpowell** [comment]
OK
