### ISSUE TITLE
renderData() reset kills sessions

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#361]
The change introduced in #342 causes session cookies to be killed. Should this just be removed or made conditional or...?

**Comment by seancorfield** [comment]
My personal feeling is that this wasn't a common enough bug to really need a fix in the first place so I would lean toward deleting that line -- folks just need to be careful when debugging a REST API!

Thoughts @GiancarloGomez ?

**Comment by GiancarloGomez** [comment]
Hey @seancorfield,

I believe I use this in a production scenario and I have not had issues with session cookies. I know before this was available I was doing something very similar with functions that I normally extend fw/1 with (an old kind of base for me). If it is causing an issue though I say remove it but I would like to see an example, it is really just a simple cfcontent reset per say (at least how I understood it).

**Comment by seancorfield** [comment]
Initial testing and responses from folks seem to indicate this does **not** kill session cookies and it may be something in @davidsf's testing setup. Additional investigation is being done.

**Comment by seancorfield** [comment]
@davidsf confirmed this is an issue with his test setup only. Closing.

**Comment by seancorfield** [comment]
It turns out this `reset()` call has a problem related to headers that I've just run into at work. It removes any headers an application sets, such as cross-origin permissions. Because of that, I'm going to revert this in 3.5 and may even back port this removal to 3.1.

**Comment by GiancarloGomez** [comment]
Makes sense. Sorry thought it was a good idea. I wonder if it happens with ACF function instead, no reason to keep in but do wonder.
