### ISSUE TITLE
ioclj is too limited in recognizing plurals

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#366]
Currently only `{something}s` is recognized as a plural of `{something}`. It would be nice to recognize more types of plurals. At least `{something}ies` as the plural of `{something}y`. (e.g., utilities, libraries).

It would also be nice to be more flexible with the name segments since right now we require

    top-level.optional.middle.segment.singulars.namespace

and we turn this into just:

    namespaceSingular

As I start to work with this at World Singles, it would be nice to have something like:

    top-level.some.ignored.optional.stuff.singulars.more.stuff.to.the.namespace

i.e., spot the first plural after the `top-level` segment, and roll up everything afterward:

    moreStuffToTheNamespaceSingular

This would move the uniqueness constraint to the whole `moreStuffToTheNamespace` piece instead of just `namespace` which would avoid collisions and make injected names more descriptive.

**Comment by jcberquist** [comment]
Just a thought: what about specifying the endings in the config? It seems like it could be relatively simple since only the endings are needed. Though the order would matter, since `ies` ends in `s`. So something like:
```
variables.config.pluralEndings = [  { 'ies': 'y' }, { 's': '' } ]
```

**Comment by seancorfield** [comment]
I don't want to make this _too_ customizable: you already have `singulars` to specify irregular plural -> singular mappings (e.g., pride -> lion :) per the docs). We've gotten by with just one regular plural -> singular mapping for years and I'm the first person to find a need for an additional regular mapping, and it's because I'm integrating two large code bases and need to be able to distinguish between `user.clj` as some sort of "service" and `user.cfc` as an existing service. Since Clojure namespaces aren't really objects, even tho' they sort of look like singletons to CFML, calling them "libraries" makes sense -- which is what led me to wanting `ies` -> `y` so `worldsingles/libraries/user.clj` becomes `userLibrary` as an injected entity.

**Comment by seancorfield** [comment]
Also, this ticket is much more about using more parts of the Clojure namespace in the injected bean's name. The expansion of singular -> plural mappings is really more of a distraction. And I had originally planned to do it only as a special case, just for `ioclj.cfc` (by adding `boolean liberal = false` as an optional argument to `singular()` in DI/1). I implemented that way at first. Then decided to make it a DI/1 config setting, so this has already suffered scope creep :)

**Comment by jcberquist** [comment]
Makes sense, thanks for responding. I do use the `singulars` config setting, and that works well. It just occurred to me when I saw the commit for ioc.cfc :).

**Comment by seancorfield** [comment]
BTW, just to show how even adding `pluralEndings` won't get you too much further, read over https://en.wikipedia.org/wiki/English_plurals and consider the plurals of `witch` and `judge` (so you can't rely on a rule for `es` -> `s` since `judges` would become `judg`).

**Comment by jcberquist** [comment]
Ah yes, good point.

**Comment by Richardtugwell** [comment]
Yeah, and what about sheep?

On 12 September 2015 at 03:37, jcberquist <notifications@github.com> wrote:

> Ah yes, good point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/framework-one/fw1/issues/366#issuecomment-139703683>.
>



-- 
=================================
Richard Tugwell
http://blog.richardtugwell.com
r.tugwell@forthmedia.com

**Comment by Richardtugwell** [comment]
or goose....

But to be frank, I don't have many of these in my projects....

On 12 September 2015 at 09:36, Richard Tugwell <r.tugwell@forthmedia.com>
wrote:

> Yeah, and what about sheep?
>
> On 12 September 2015 at 03:37, jcberquist <notifications@github.com>
> wrote:
>
>> Ah yes, good point.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/framework-one/fw1/issues/366#issuecomment-139703683>.
>>
>
>
>
> --
> =================================
> Richard Tugwell
> http://blog.richardtugwell.com
> r.tugwell@forthmedia.com
>



-- 
=================================
Richard Tugwell
http://blog.richardtugwell.com
r.tugwell@forthmedia.com

**Comment by seancorfield** [comment]
You mean, like in these tests: https://github.com/framework-one/fw1/blob/master/tests/TransientTest.cfc#L5 :)

**Comment by Richardtugwell** [comment]
☺

On 14 September 2015 at 02:38, Sean Corfield <notifications@github.com>
wrote:

> You mean, like in these tests:
> https://github.com/framework-one/fw1/blob/master/tests/TransientTest.cfc#L5
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/framework-one/fw1/issues/366#issuecomment-139937760>.
>



-- 
=================================
Richard Tugwell
http://blog.richardtugwell.com
r.tugwell@forthmedia.com
