### ISSUE TITLE
Inconsistencies around subsystem bean factories

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#370]
This came up on Slack today and I observed:

> So `getBeanFactory("module")` requires the subsystem be setup already but won’t fail if the subsystem has no bean factory (yet) and `getSubsystemBeanFactory("module")` will setup the subsystem for you, but will throw an exception if that subsystem doesn’t create a bean factory.

I don't want to encourage reaching into subsystems to pull beans out -- they should be sealed units of functionality -- but this is a very weird / subtle distinction that should probably be ironed out.

The subsystem docs lead people to try the former and it silently delegates to the parent bean factory if the subsystem has not been initialized (hard to debug).

Part of the problem here is that `hasSubsystemBeanFactory()` does not call `setupSubsystemWrapper()` which it probably should -- but all uses should be checked for consistency (in the code and in the docs).

**Comment by seancorfield** [comment]
I think this is dealt with too now on **develop**.

**Comment by itimgit** [comment]
Dear Sean. we want to know if a subsystem is initialized, to run mxunittests on it or not. When we call hasSubsystemBeanFactory(...), that subsystem gets initialized. So how can we see if a subsystem is available, without initializing it?

fw.hasSubSystemBeanFactory("foo") -> true

**Comment by seancorfield** [comment]
There's no point in asking (unrelated) questions on a closed issue. Questions belong on the mailing list or in the #fw1 channel on the CFML Slack.
