### ISSUE TITLE
View does not behave as expected when used inside a subsystem.

### ISSUE THREAD

**Issue by sneiland** [framework-one/fw1#373]
As of 3.5 beta2 calling view("section/item") does not resolve to being relative to the subsystem / main app where it is called.

Expected behavior view(":section/item") should point to main app views directory while omitting the colon should make the path relative to the subsystem.

**Comment by msp1kpj** [comment]
I have a similar issue with access in the default page. The default variables.framework.home variable is  being set to ":main.default" but the getFullyQualifiedAction method says that if subsystem is emtpy  do not include the subsystem delimiter.

**Comment by seancorfield** [comment]
The setting of `variables.framework.home` is correct -- I suspect the docs need to be updated to say it should be "the same as calling http://framework-one.github.io/documentation/3.5/reference-manual.html#public-string-function-getsubsystemsectionanditem-string-action--requestaction- " now.

**Comment by seancorfield** [comment]
I believe this is fixed in the **develop** branch now.
