### ISSUE TITLE
`redirect()` does not accept a struct for the `queryString` argument

### ISSUE THREAD

**Issue by U47** [framework-one/fw1#383]
A struct is permitted for `queryString` in the `BuildURL()` method, yet not in the `redirect()` method. Seems like an easy fix for consistency.

```
BuildURL(action = 'sprocket.edit', queryString = {'id' = someVar, 'parent' = someOtherVar});
```

works, but

```
redirect(action = 'sprocket.edit', queryString = {'id' = someVar, 'parent' = someOtherVar});
```

doesn't.

My 2¢.

**Comment by seancorfield** [comment]
That does seem like a good idea and it looks fairly easy to add (I can just copy the `queryString` struct-to-string code from `buildURL()` into `redirect()` -- or rather make it a helper function and call it in both places!).

**Comment by U47** [comment]
For sure. As a workaround, I'm just calling `BuildURL` with an empty string as the `path` and feeding that into `redirect()`.

Not a huge deal.

**Comment by seancorfield** [comment]
Added to *develop* branch. This will be in FW/1 3.5. :+1:

**Comment by seancorfield** [comment]
Documentation updated (Reference Manual for 3.5).

**Comment by U47** [comment]
Hi @seancorfield. Did this regress in v4.0?

```
Error: The QUERYSTRING argument passed to the redirect function is not of type string.
```

**Comment by seancorfield** [comment]
Looks like it was never fixed properly: https://github.com/framework-one/fw1/blob/develop/framework/one.cfc#L1065 -- still has `string` as the data type of the argument, even tho' the code _inside_ the function accepts a struct. Reopening.

**Comment by seancorfield** [comment]
This commit should solve it 3f3db9479720e6113b12d3e32b54a0216c8b77b9 and it'll be in 4.1.
