### ISSUE TITLE
Possible thread safety issue in setupRequestDefaults()

### ISSUE THREAD

**Issue by jcberquist** [framework-one/fw1#384]
I have just updated a couple of apps to 3.5.0-rc2, and I think that this commit: https://github.com/framework-one/fw1/commit/cbb5a715292d3499e26fb0fa90ba004e4c1099f7 may have introduced a thread safety issue. I am seeing a number of errors that state:
```
key [applicationKey] doesn't exist (existing keys:generateSES,reloadApplicationOnEveryRequest,base,trace,diConfig,password,diLocations,SESOmitIndex,maxNumContextsPreserved)

framework/one.cfc:1806
framework/one.cfc:894
```
As far as I can tell, this only happens on the first request of a session, when the server is handling multiple requests at the same time. It makes me think that `onSessionStart()` is not thread safe - and so sometimes `request._fw1.requestDefaultsInitialized` will be `true` when `setupRequestDefaults()` is called at the start of `onRequestStart()` but the `variables.framework` struct will not have been initialized for that request.

I created the following simple `Application.cfc` to mimic the setup of framework one, and hit it with some simultaneous requests (via JMeter):
```
component {

	this.name = 'testApp';
	this.sessionManagement = true;
	variables.config = { };

	request.configDataSet = false;

	function onSessionStart() {
		setConfigData();
	}

	function onRequestStart( string targetPage ) {
		setConfigData();
		writeOutput( serializeJSON( variables.config ) );
	}

	function setConfigData() {
		if ( !request.configDataSet ) {
			variables.config.data = now();
			request.configDataSet = true;
		}
	}

}
```
Often it takes only a few simultaneous threads before `variables.config.data` will be missing from the output for some of the threads. I should add I ran this test on Lucee 4.5.2.017, and I suppose it is possible that this is an issue with Lucee, not FW/1.

**Comment by seancorfield** [comment]
Thanks @jcberquist -- I'll do some digging. It does sound more like a Lucee issue than a FW/1 issue because there should be a new instance of `Application.cfc` for every request and the request that starts the session should be a unique instance (that has both `onRequestStart()` and `onSessionStart()` called on it).

**Comment by seancorfield** [comment]
OK, the only way I can see this happen is if `request` scope is shared between the first request in a session and the session startup logic itself but those two somehow get unique `variables` scope -- which definitely sounds like a Lucee bug to me.

I've made a small change to how `setupFrameworkDefaults()` is called and used. Could you pull down the latest **develop** branch code and try it again?

**Comment by jcberquist** [comment]
Thanks @seancorfield, will do. I agree with you that this is a Lucee bug. I tried the same test on CF11 and I have not been able to get the error at all.

**Comment by seancorfield** [comment]
Good to know. Have you logged it as a bug on Lucee's JIRA? Seems like you have a nice, simple, self-contained test case.

**Comment by jcberquist** [comment]
I think I will log this as a bug. I have been trying to make the smallest example I can. What do you think of the following:
```
component {

	this.name = 'testApp';
	this.sessionManagement = true;

	variables.templateId = createUuid();

	function onSessionStart() {
		request.templateId = variables.templateId;
	}

	function onRequestStart( string targetPage ) {
		writeOutput( "variables.templateId: " & variables.templateId );
		writeOutput( chr(10) );
		writeOutput( "request.templateId: " & request.templateId );
	}

}
```
If I run 20 or so new session requests against that, there always seems to at least one case, if not several, where `variables.templateId` does not match `request.templateId` in the output. Instead, `request.templateId` will match the `variables.templateId` of another request. So it seems to me like the one request is using the same variables scope as another request in `onSessionStart()`. Does that seem right to you?

**Comment by seancorfield** [comment]
Yup, that sounds right (i.e., you've identified a bug). Have you tried my workaround on the **develop** branch? Given the bug in Lucee, I don't know if it will successfully fix the problem but I _think_ it should make it less likely (I've decoupled the framework settings update from the request defaults update, using a `variables` scope flag for the former and a `request` scope flag for the latter).

**Comment by jcberquist** [comment]
Thanks for looking it over, and yes, I have deployed your workaround. I will let you know if the error recurs. And thanks for getting the workaround out so quickly!

**Comment by jcberquist** [comment]
Just a quick update - I did report this: https://luceeserver.atlassian.net/browse/LDEV-571. Also, I have not seen any recurrence of the error since deploying your workaround. Given the rate at which the errors were occurring, I am confident that your workaround has taken care of the issue, and as far as I am concerned this issue can be closed. Thanks again for the quick response!

**Comment by seancorfield** [comment]
Excellent news! Thank you for testing that and reporting back so quickly.
