### ISSUE TITLE
Support application/json POSTs

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#389]
Requested by a couple of people (including World Singles).

Need to be able to accept `Content-Type: application/json` and a JSON body (which may be binary on certain CFML servers!) and unpack it into `rc` at the start of the request.

**Comment by seancorfield** [comment]
Implemented in 3.6 on **develop**.

**Comment by seancorfield** [comment]
Doesn't account for `charset` etc in the `Content-Type`.

**Comment by carltonsmith** [comment]
Is there any documentation on how this works? I am testing this using the Firefox REST client and I'm showing rc as containing none of the JSON data at all? Do I need to deserialize? If so, what do I need to deserialize?

**Comment by seancorfield** [comment]
Please don't use old, closed issues for support questions -- post on the FW/1 mailing list or join the CFML Slack and ask in the #fw1 channel there. That way your question will get in front of hundreds of folks who can help you. Thanks.
