### ISSUE TITLE
When using `$RESOURCES` as routes, a malformed `DELETE` (missing an ID) will result in a mismatching action

### ISSUE THREAD

**Issue by mjhagen** [framework-one/fw1#392]
_(as posted on the CFML Slack's #fw1)_

This makes sense, but I would like the framework to account for that and maybe provide a better way handling expected errors in routes.

Example:
I have a subsystem with my API in it (api:) and when I call this URL: `DELETE /api/myObject/1` that will be rewritten by fw/1 to `api:myObject.destroy?id=1` but when I call `DELETE /api/myObject` it gets rewritten to `defaultsubsystem:api.myObject` where I would like it to recognize the pattern and either throw a 404 or a 500 (I'm not sure which is more RESTful).

**Comment by mjhagen** [comment]
I've created an example app displaying this behavior: https://github.com/mjhagen/SSCCE/tree/master/fw1-392
The http call is in views/main/default.cfm

**Comment by seancorfield** [comment]
:+1:

**Comment by seancorfield** [comment]
A possible solution here is to allow per-resource error handling. You can try this by setting the resource template in you configuration: copy the framework default and add a line that has a method of "error" and matches the http method "$*". This will route anything that "almost matches" to /api:myObject/error so you can do better handling. 

I think I'll add a perResourceError flag to enable this in core. How does that sound?

I could just add that as the default and let folks who want the old behavior set it false I guess. This is a 4.0 release after all.

**Comment by seancorfield** [comment]
Try the **develop** branch version and see how you like that: it implements the per-resource error handling described above.

**Comment by seancorfield** [comment]
@mjhagen Any thoughts on this new error-handling behavior?
