### ISSUE TITLE
Request: throw error on autowired DI beans containing syntax errors.

### ISSUE THREAD

**Issue by mjhagen** [framework-one/fw1#394]
I have a controller with a `property` pointing to a service bean that has a syntax error in it. The framework doesn't throw this error, it just doesn't set the property. Later on I get an exception about the missing variable, but I would like it to show me where the syntax error occurred.

I've written some code that demonstrates this here: https://github.com/mjhagen/SSCCE/tree/master/fw1-394

It has two actions: `?action=main.default` and `?action=main.exception`, the last one results in "Variable BREAKSTUFFSERVICE is undefined."

**Comment by seancorfield** [comment]
Are you sure your controller is managed by DI/1? If you call `beanfactory.load()` that will force all beans to load and you should get syntax errors shown. 

If your controller is not managed by DI/1 then it's FW/1 doing the auto wiring and it's possible that swallows exceptions.

**Comment by mjhagen** [comment]
I think it's an FW/1 thing, but I must say I'm still very much a novice if it comes to anything DI.
The app is setup with only `framework.diLocations` and an autowired bean in the main controller, no beanfactory.load().

**Comment by seancorfield** [comment]
What's in `diLocations`?

**Comment by mjhagen** [comment]
`variables.framework.diLocations = "services";`

**Comment by seancorfield** [comment]
OK, then your controllers are not managed by DI/1 and this is FW/1's old autowiring code that's hiding the syntax error.

Change that to `variables.framework.diLocations = "controllers, services";` and see if you get the syntax error?

**Comment by seancorfield** [comment]
(sorry for the questions, I didn't notice that your link was to a complete app until just now)

**Comment by mjhagen** [comment]
Changed it, but it doesn't throw the error. The syntax error is in services/breakstuff.cfc btw.

**Comment by seancorfield** [comment]
Thanks for double-checking. Will clone your repo and take a deeper look this weekend.

**Comment by mjhagen** [comment]
:+1:

**Comment by seancorfield** [comment]
When I run that, I get:
```
FW/1 version: 4.0.0-snapshot

Framework reloaded: false

Test result: Works!
```

**Comment by seancorfield** [comment]
I edited `Application.cfc` to remove `controllers` from `diLocations`, restarted Lucee 4.5.2, and it still worked.

What version of FW/1 are you on? What CFML engine / version?

**Comment by mjhagen** [comment]
CF11, I provided 2 actions, one that results in the "Works" message, the other (action=main.exception) wich results in the (wrong-ish) error

**Comment by seancorfield** [comment]
Ah, that was not clear. Thanks. Will try that.

**Comment by seancorfield** [comment]
Here's the exception you would get now:

Problem with metadata for breakstuff (tests.SSCCE.fw1-394.services.breakstuff) because: Unable to getComponentMetadata(tests.SSCCE.fw1-394.services.breakstuff) because: Syntax Error, Invalid Construct, near line 3 in /Developer/workspace/fw1/tests/SSCCE/fw1-394/services/breakstuff.cfc
