### ISSUE TITLE
controllers with the word controller

### ISSUE THREAD

**Issue by jmohler1970** [framework-one/fw1#396]
It should be possible to create controllers that have controller at the end of their name and have that name stripped off. Examples

```
controllers/pageController.cfc
controllers/settingsController.cfc
controllers/supportController.cfc
```

Would be the same as

```
controllers/page.cfc
controllers/settings.cfc
controllers/support.cfc
```

**Purpose**

Many, if not most text editors, only show the file. It is highly likely that a controller name is also a model name or something else. By adding appending controller to the name, the file becomes unambiguous.

Furthermore, I propose that if both a plain controller with controller with controller in its name exist, this will throw an error.

**Comment by seancorfield** [comment]
This is the opposite of the current conventions. Not doing this. Use a better editor :)
