### ISSUE TITLE
Refactor Application.cfc lifecycle to separate CFC

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#397]
Consider a separate (convention-based) CFC that is used to define all the (current) `Application.cfc` extension points and what it means for some of those to be per-subsystem as well as per-application. This is somewhat of a parent ticket for 5.0 and there will likely be child tickets to address specific changes.

**Comment by seancorfield** [comment]
In order to provide a migration path -- depending on exactly how this is implemented -- we may need a 4.5 release with appropriate deprecations and a settings.

**Comment by jmohler1970** [comment]
Can you give an example of the expected before and after on this? What is the problem that it is trying to solve?

**Comment by seancorfield** [comment]
No. That's why it "needs analysis" and is slated for 5.0.

The current setup -- the way the framework has been since day one -- leads to an ugly mix of application code and lifecycle code. Even when moving to the **Alternate Application Structure**, you still end up with a lot of application code in with the framework configuration and that "feels wrong" from a design point of view.

I don't know what the right design is yet, but the status quo is definitely wrong.

**Comment by bardware** [comment]
Do I see right: when `fw` is injected to a controller, the one instance created by the first request to the application is being injected?

**Comment by seancorfield** [comment]
@bardware That doesn't seem like a question that is relevant to this GH issue? If it's a general question, it belongs on the mailing list (or on Slack).

**Comment by seancorfield** [comment]
See http://framework-one.github.io/blog/2019/03/27/fw1-roadmap/
