### ISSUE TITLE
Add ASL2 LICENSE / update README

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#410]
SSIA. @ryanguill pointed out that even tho' the `framework/*` files include the ASL2 license / copyright text, there's no overall license file or any indication in the readme about the software license. Should probably review / update contributing page too.

**Comment by ryanguill** [comment]
might be something to consider adding to http://framework-one.github.io/ as well?

**Comment by seancorfield** [comment]
Well, the docs should be Creative Commons etc, but they should probably mention that FW/1 itself is ASL2.
