### ISSUE TITLE
Request header handling in FW/1 v4.0

### ISSUE THREAD

**Issue by jcberquist** [framework-one/fw1#411]
With the increased focus on REST support coming in FW/1 v4, it could be a good idea for the framework to provide access to request headers. It is true that it is easy to get at request headers via the `getHttpRequestData()` method. However, I think it would be appropriate for the framework to add a framework specific way for handling headers, since it is highly likely that any REST API is going to need to access request headers. (Just as FW/1 provides easy and framework specific access to FORM and URL scope variables in the `rc` struct today.)

A couple of possibilities are:
- adding a new `getHeader()` method, that controllers can use to access specific headers
- passing a headers struct to controller methods as a second argument so that controller methods would have the form `controllermethod( rc, headers ) {}`

I would be interested in any feedback or thoughts that people have.

**Comment by seancorfield** [comment]
After looking at how controllers were invoked, it was easy enough to add `headers` as a second argument (third argument to `onMissingMethod()`). Now to update the documentation!

**Comment by jccsbenjamin** [comment]
Has any progress on this. With xhr level2 this would be very helpful.

**Comment by seancorfield** [comment]
I'm not sure what you're asking -- this was implemented and documented as part of the 4.0.0 release cycle which is currently at Beta 2 status (and we've had 4.0.0 in production for months so I'd consider it very stable).

**Comment by seancorfield** [comment]
@jccsbenjamin ^ Just making sure you saw my comment?

**Comment by jccsbenjamin** [comment]
Thank, you.
