### ISSUE TITLE
Expose cgiRequestMethod variable for convenience 

### ISSUE THREAD

**Issue by aliaspooryorik** [framework-one/fw1#419]
A small suggestion for an enhancement although it is easy to access the information by other means.

Internally FW/1 stores the `CGI.REQUEST_METHOD` as `cgiRequestMethod`. As this key is already in FW/1 it could be made available via a method so that controllers could access it (something like `variables.fw.getRequestMethod()`).

My use case for this was that I had a request coming in which was being handled by the controller queued from `setupRequest`. I wanted to know the http verb so that I could check for a CSRF token for POST / DELETE / PUT requests.

**Comment by seancorfield** [comment]
Yes, this seems like a very reasonable enhancement. I'll add `getCGIRequestMethod()`.
