### ISSUE TITLE
Beans added by addBean() not injected in sub application

### ISSUE THREAD

**Issue by am2605** [framework-one/fw1#423]
After upgrading from 3.1 to 3.5 I've run into an issue where properties declared in setupApplication with "getBeanFactory.addBean(...)" don't get injected.  It seems to only happens when using subsystems (old style - haven't tried the new ones) .  

The issue also can be reproduced against the current develop branch.

A sample app displaying this behaviour is available at https://github.com/am2605/fw1-subapp-demo

**Comment by am2605** [comment]
Sean - I can get the desired behaviour by calling getDeafultBeanFactory() rather than getBeanFactory() in my setupApplication method.

Perhaps this is actually the correct way to do things, as it looks like getBeanFactory() will actually return the default subapp's beanFactory.  So I'm tempted to say the current behaviour is actually fine and close this issue.   Do you agree?

**Comment by seancorfield** [comment]
I want to keep this open until I've figured out what caused the behavior change since it wasn't intentional (calling `getBeanFactory()` in `setupApplication()` should always get the default factory -- calling it in `setupSubsystem()` should always return the subsystem-specific factory -- that's the principle of least surprise).

**Comment by seancorfield** [comment]
Based on @am2605 's comment three years ago, I think I'd be happy closing this, even tho' it seems to be an unintentional change in behavior -- there's a clear workaround so perhaps just adding a note to the documentation for `getBeanFactory()` and/or subsystems to make it clear that `getDefaultBeanFactory()` should be used in `setupApplication()` instead. @sneiland

**Comment by sneiland** [comment]
Im going to keep this open for now as something to address when/if we get to 5.0 but it wont be addressed in any 4.x release

**Comment by sneiland** [comment]
After looking at the roadmap its probable that the 5.0 release will want to change/add to the setup subsystem logic regardless so this will no longer be relevant in that scenario.
