### ISSUE TITLE
Suggest adding "fw1-dev" on ForgeBox for develop repo

### ISSUE THREAD

**Issue by cfchef** [framework-one/fw1#425]
There are currently 2 methods of installing FW/1 via CommandBox/ForgeBox: `box install fw1` (stable) and `box install fw1-3.5.0` (which at the time of creation was dev).

The packages are identical right now. My opinion is that if I want to install the current develop version of FW/1, entering `box install fw1-dev` is simpler. This saves having to know the current develop version number and also kills the current situation where the dev package version isn't even correct at this time.

Changing the location key in `box.json` to `https://github.com/framework-one/fw1/archive/develop.zip` would be a one time change (aside from updating master for stable releases). Maintenance of the package would be slimmed down to simply updating the version number in box.json and ForgeBox (as far as I know). Another one time change would be changing the dev package name and slug on ForgeBox (otherwise create a new package and scrap the "fw1-3.5.0" package).

I can do a PR for the box.json in develop but obviously cannot make changes on ForgeBox unless I make a new package myself.

Thoughts?

**Comment by seancorfield** [comment]
Good idea. This has always bothered me and what I originally did was just a workaround for ForgeBox not supporting versioned projects properly (and it's been on the roadmap for ages I was told).

**Comment by cfchef** [comment]
PR started. #426

**Comment by seancorfield** [comment]
`install fw1-dev` has been set up at ForgeBox for installing the develop branch version, thanks to your PR!

**Comment by seancorfield** [comment]
I should probably update the README to show installation via CommandBox. Or perhaps the Getting Started documentation. Thoughts? Suggestions?

**Comment by cfchef** [comment]
Def in the docs (readme wouldn't hurt either). I think adding info about it at the beginning of the "your first fw/1 app..." section or making a whole new section before it explaining installation methods would work. I'll look into it more when I get a chance and see about tackling that in the next day or two.

**Comment by seancorfield** [comment]
Thank you!

**Comment by cfchef** [comment]
Updates to docs - https://github.com/framework-one/framework-one.github.io/pull/20

**Comment by seancorfield** [comment]
Closed by PR on docs.
