### ISSUE TITLE
Bug on parseViewOrLayoutPath

### ISSUE THREAD

**Issue by henriquefeijo** [framework-one/fw1#429]
On Version 3.5 there is a bug on line 1870, 1872 and 1874.  (I suspect the bug is on version 3.x)

The line:

`if ( !cachedFileExists( expandPath( defaultPath ) ) )`

should be:

`if ( !cachedFileExists( defaultPath ) )`

Since cachedFileExists already performs an `expandPath()` inside the function. By doing this the cache is never created because of the double `ExpandPath()` being executed. After I fixed on my side, my website is running a lot faster now when `"cacheFileExists = true"`

**Comment by seancorfield** [comment]
Thanks. Fixed on **develop**. Will be in next Alpha or first Beta.
