### ISSUE TITLE
Add wildcard route mapping

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#432]
Currently `/:section/:item` and `/:section` and `/` can match "anything" (well, any 2+ part URL, any 1+ part URL, and any URL, respectively). But they leave the unmatched part of the URL as query parameters. We need a `*` pattern that eats the whole URL path.

**Comment by jmohler1970** [comment]
Can you give more examples on the change in behavior?

**Comment by seancorfield** [comment]
Darn, I opened this against FW/1 for CFML -- should have been against FW/1 for Clojure!
