### ISSUE TITLE
FW/1 3.5.1 release lists version as 4.0.0 snapshot

### ISSUE THREAD

**Issue by jmohler1970** [framework-one/fw1#433]
I followed the link on this page:

https://github.com/framework-one/fw1/releases/tag/v3.5.1

Downloaded the zip and noted that

`/framework/one.cfc`

Starts with

```
component {
    variables._fw1_version = "4.0.0-snapshot";
/*
    Copyright (c) 2009-2016, Sean Corfield, Marcin Szczepanski, Ryan Cogswell
```

**Comment by seancorfield** [comment]
Thanks. **master** had the correct code but the release was accidentally built against **develop** instead. I've rebuilt release 3.5.1 on **master** now.

**Comment by jmohler1970** [comment]
Confirmed to work on CF 9.01

**Comment by seancorfield** [comment]
Per the docs "FW/1 3.5 supports Adobe ColdFusion 9.0.2 or later (not 9.0.0 or 9.0.1). ... If you’re on ColdFusion 9.0.1, FW/1 3.5 should work but there may be some edge cases in Application.cfc lifecycle behavior that may trip you up."
