### ISSUE TITLE
Rename enableJSONPOST

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#442]
This is poorly named since it enables more than just JSON support and it does it for all HTTP verbs, not just POST. A better name would be `enableRESTbody` but I'd like feedback from the community on this.

Note that it will be a **breaking** change for anyone using `enableJSONPOST` so that option needs to throw an exception at startup to avoid silent changes of behavior.

**Comment by Richardtugwell** [comment]
I'm using this to POST data that isn't strictly REST-ful - e.g objects that
could encapsulate form data + other stuff for example. So I'm not sure
about having REST in the name...

On 11 July 2016 at 20:58, Sean Corfield <notifications@github.com> wrote:

> This is poorly named since it enables more than just JSON support and it
> does it for all HTTP verbs, not just POST. A better name would be
> enableRESTbody but I'd like feedback from the community on this.
>
> Note that it will be a *breaking* change for anyone using enableJSONPOST
> so that option needs to throw an exception at startup to avoid silent
> changes of behavior.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/framework-one/fw1/issues/442>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABJDLV9b8Ky-keVgsWntDuw4OZxkliI3ks5qUqBqgaJpZM4JJuSH>
> .
>



-- 
=================================
Richard Tugwell
http://blog.richardtugwell.com
r.tugwell@forthmedia.com

**Comment by Richardtugwell** [comment]
Naming is really tough....

On 11 July 2016 at 21:26, Mingo Hagen <notifications@github.com> wrote:

> Is enableHTTPbody better?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/framework-one/fw1/issues/442#issuecomment-231854014>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABJDLXaETSefiysOOtDfhMcoWjIAL_O3ks5qUqcSgaJpZM4JJuSH>
> .
>



-- 
=================================
Richard Tugwell
http://blog.richardtugwell.com
r.tugwell@forthmedia.com

**Comment by seancorfield** [comment]
`enableEncodedBody` perhaps? Or `enableBodyDecoding`?

👍 on naming being really tough!

**Comment by jcberquist** [comment]
To offer another opinion here - I like having `decode` in the name. Both `enableHTTPBodyDecode`  and `enableHTTPBodyDecoding` sound good to me, though perhaps they are a bit long. @seancorfield's simpler/shorter suggestion of `enableBodyDecoding` sounds good too.

**Comment by Richardtugwell** [comment]
It's just personal but I prefer 'doSomething =  true|false' rather
than 'enableDoSomething = true|false'

So maybe parseRequestBody?

On 12 July 2016 at 01:16, jcberquist <notifications@github.com> wrote:

> To offer another opinion here - I like having decode in the name. Both
> enableHTTPBodyDecode and enableHTTPBodyDecoding sound good to me, though
> perhaps they are a bit long. @seancorfield
> <https://github.com/seancorfield>'s simpler/shorter suggestion of
> enableBodyDecoding sounds good too.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/framework-one/fw1/issues/442#issuecomment-231903314>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABJDLTIaeesLDDpx80OvFPyNRr9szY2tks5qUtzmgaJpZM4JJuSH>
> .
>



-- 
=================================
Richard Tugwell
http://blog.richardtugwell.com
r.tugwell@forthmedia.com

**Comment by mjhagen** [comment]
Wouldn't that be `decodeRequestBody` then @Richardtugwell? Though parsing is broader than decoding I guess.

**Comment by Richardtugwell** [comment]
Yeah - I'd be happy with that. Parse is a bit vague

On 12 July 2016 at 10:56, Mingo Hagen <notifications@github.com> wrote:

> Wouldn't that be decodeRequestBody then @Richardtugwell
> <https://github.com/Richardtugwell>? Though parsing is broader than
> decoding I guess.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/framework-one/fw1/issues/442#issuecomment-231993441>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABJDLfXepiIk0cSwZQQxxZYootXkib80ks5qU2S8gaJpZM4JJuSH>
> .
>



-- 
=================================
Richard Tugwell
http://blog.richardtugwell.com
r.tugwell@forthmedia.com

**Comment by seancorfield** [comment]
FWIW, FW/1 has used `enableXyz` settings in the past, although it has also used `suppressAbc` (but usually in transition as features are deprecated and phased out). I'd be happy with `decodeRequestBody` tho'.

**Comment by jcberquist** [comment]
`decodeRequestBody` sounds good to me, too.

**Comment by cfchef** [comment]
I'm for `decodeRequestBody` 👌🏻

**Comment by cfvonner** [comment]
`decodeRequestBody` works for me.

**Comment by ddspringle** [comment]
+1 for `decodeRequestBody`

**Comment by seancorfield** [comment]
OK, `decodeRequestBody` it is!

**Comment by seancorfield** [comment]
This has been applied to the **develop** branch. Given the "breaking" nature of this, I think I'm going to cut Beta 2 and update the documentation.
