### ISSUE TITLE
Invalid buildUrl() when baseUrl ends with a trailing "/"

### ISSUE THREAD

**Issue by Tyf0x** [framework-one/fw1#452]
My links will include a double "/" in their url if I declare 

```
variables.framework.baseURL = "http://" & cgi.HTTP_HOST & "/myapp/"
```

I feel like having a base URL ending with a trailing slash shouldn't lead to this issue?

Thoughts?

**Comment by seancorfield** [comment]
Given that FW/1 goes to the trouble of removing trailing slashes elsewhere so they can be optional, you're right that it probably ought to remove them here as well. Good catch!

**Comment by cfchef** [comment]
@seancorfield, as far as documenting this goes, would you suggest that there just be a note stating a trailing slash will be removed? Here? -> http://framework-one.github.io/documentation/4.1/reference-manual.html#public-string-function-getbaseurl

**Comment by seancorfield** [comment]
I think a better place to document it would be around the `baseURL` framework setting but I haven't decided yet (the "needsdocumenting" label is just a reminder to me to make sure the ticket gets onto the change log and for me to decide what else needs updating).

**Comment by cfchef** [comment]
Ah. Gotcha.
