### ISSUE TITLE
sub beans are treated as singletons.

### ISSUE THREAD

**Issue by cybersonic** [framework-one/fw1#459]
I am not sure if this is a feature or a bug (sounds like a bug to me

**Given** that I have the following folder structure:

- model
 - beans
    - Bean.cfc
    - subbeans
        - SubBean.cfc

**And** I configure DI1 to get them as:
```
ioc = new framework.ioc("/model");
```
**And** that `Bean` and `SubBean` are coded as follows:
```
component {
	this.id = CreateUUID();
}
```
**Then** I expect that multiple calls to `ioc.getBean('Bean')` result in each bean having a different ID  (this works obviously) 
**And** I also expect that multiple calls to `ioc.getBean('SubBean')` also results in each bean having a different ID.  This **fails** at the moment and the SubBean is treated as a singleton. 

Is this expected behaviour? I would guess not?

The test code is as follows (in one cfm without application) :

```
<cfscript>
	ioc = new framework.ioc("/model");

	dump([ioc.getBean("Bean"),ioc.getBean("Bean")]);
	dump(ioc.getBean("Bean").id EQ ioc.getBean("Bean").id); //Should be false
	dump([ioc.getBean("SubBean"),ioc.getBean("SubBean")]);
	dump(ioc.getBean("SubBean").id EQ ioc.getBean("SubBean").id); //Should be false but is true
</cfscript>
```

**Comment by seancorfield** [comment]
Only the direct parent folder affects how a CFC is treated. You'll need to add `subbeans` to your list of transient folders in the DI/1 configuration to get the behavior you want.

**Comment by cybersonic** [comment]
This is non-obvious in the documentation. Maybe add that any CFC who's parent folder is called "beans" is treated as a transient. 

Will see if I can update the docs where it would be obvious. 

So instead of having folders like:

	model
		beans
			package
			package2
		services
			package
			package2

(which is how I expected DI to work) 

It might be better practice to have 

	model
		package
			beans
			services
		package2
			beans
			services


Is this the intention?

**Comment by seancorfield** [comment]
Yes, the second structure is closer to the intention since it groups transients and non-transients together by purpose / packge.
