### ISSUE TITLE
Consider missingView as action

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#460]
This arose from #fw1-clj/51 which is looking at a missing view handler for the Clojure version. Given that the default error handling is an actual action (where we reset everything and run a new action), could missing view be handled in a similar way? This would probably be more flexible (and more consistent) than the current missing view handling machinery.

**Comment by dnando** [comment]
This makes sense to me. It always seems overdone to throw an error in this
case - only to report that a view does not exist.



Aria Media Sagl
+41 (0)76 303 4477 cell
skype: ariamedia

**Comment by seancorfield** [comment]
Well, technically the exception is still thrown, but this allows you to specify a different error action to handle it. This is "simpler" since the new `missingview` action will occur in a fresh context from start to finish, just like a regular action (just as `error` actions work now). Previously, you could only intercept the `view()` call (essentially) and you had to just return a rendered view directly.

**Comment by dnando** [comment]
Cool. I look forward to putting this new feature to use.



Aria Media Sagl
+41 (0)76 303 4477 cell
skype: ariamedia

**Comment by seancorfield** [comment]
FYI @dnando when you reply by email to a GH comment, your phone number and Skype handle end up publicly visible in these threads. I've edited them out above but wanted to let you know.

**Comment by dnando** [comment]
Thanks Sean
