### ISSUE TITLE
Switch Travis over to CommandBox / TestBox

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1#465]
See https://github.com/coldbox-modules/cbox-i18n

**Comment by cfchef** [comment]
Hey @seancorfield,

I had started working on trying to get this functioning a while back but only got so far. Was focusing on testing locally as some tests were failing for me; and my "TestBox/testing in general" knowledge is rather meh :/

I did get Travis to talk with fw1/commandbox/testbox in my forked repo. If ya wanna take a look at what I started, I pushed my attempted changes here -> https://github.com/cfchef/fw1

If there's anything I can do to help just let me know.

Cheers.

**Comment by seancorfield** [comment]
Thanks. Will take a look at both yours and the ColdBox module that jclausen pointed me at and see what I can synthesize from both.

**Comment by cfchef** [comment]
👍🏻

**Comment by seancorfield** [comment]
Thank you @cfchef That was pretty much exactly what I needed:

https://travis-ci.org/framework-one/fw1/jobs/204814689

**Comment by seancorfield** [comment]
This was the big commit https://github.com/framework-one/fw1/commit/e35fe69451fa6a8d7698b7aaef108835bfde06e4 (I forgot to tag it with the issue number).
