### ISSUE TITLE
rc values not preserved across redirect in current 4.1 snapshot

### ISSUE THREAD

**Issue by dnando** [framework-one/fw1#469]
The introduction of the sessionRead(), sessionWrite() etc functions in 4.1 seems to have broken preserved rc values across a redirect. 

For example, using 4.0 (and any earlier version of FW/1) this redirect preserves rc.errors in an existing app I'm maintaining:

`variables.framework.redirect('main.default', 'errors');`

However, if I bump fw/1 up to 4.1 using the current snapshot, the redirect works as it should, but _errors_ is not present in _rc_

Rolling back to 4.0 again fixes the issue. 

Checking through the redirect() function in one.cfc using a diff between 4.0 and 4.1 to see if I could work out what was wrong, it seemed to me the issue may actually be located in the changes made to saveFlashContext().

**Comment by atuttle** [comment]
I'm able to reproduce this locally. Since I broke it, I'll volunteer to try and fix it. Working on that now.
