### ISSUE TITLE
Long Function Names Causing Bean Not Found Errors? 

### ISSUE THREAD

**Issue by jasperboyd** [framework-one/fw1#471]
I have the following function: 

```
<cffunction name="getAllProductsWithoutCurrentProductVersionAudits"
 				access="public"
 				returnType="any">
 				
                               <cfquery name="local.getAllProductsWithoutCurrentProductVersionAudits">
 					select * from SwProduct p 
 					where p.currentProductVersionAuditID is null
 				</cfquery> 
 				
                               <cfreturn local.getAllProductsWithoutCurrentProductVersionAudits> 
 </cffunction>
```

When I remove the get from the function name the bean not found error goes away. This is the longest function name I have in the file.

It's definitely a strange issue, let me know if you'd like more details

**Comment by seancorfield** [comment]
I expect you're getting a syntax error from ColdFusion itself -- check your console log for more information -- which causes DI/1 to ignore the CFC (since it can't load it), but this is not a restriction from FW/1.

**Comment by jasperboyd** [comment]
Yep looks like someone had removed the throw in the discoverBeans logic in ioc.cfc so we had a bunch of syntax errors failing silently. Thanks!

**Comment by seancorfield** [comment]
This was the commit (in 4.0.0) that fixed the problem you were seeing: https://github.com/framework-one/fw1/commit/1864b8064c0aa2ae6129c10558b17c763a9f2342

Note that prior to 4.0.0, the `throw except;` statement was missing(!).

That commit also improved the exception reporting around syntax errors (the first half of that commit attempts to figure out the filename & line number, which goes in the exception message).
