### ISSUE TITLE
Proposal On How FW/1 Ties Versions/Releases to ForgeBox/CommandBox

### ISSUE THREAD

**Issue by cfchef** [framework-one/fw1#483]
## Situation

I ran into an issue today with installing the development version of FW/1 using CommandBox and a project's box.json that called on `fw1-dev` as a dependency.

If you declare `fw1-dev` as a key for `dependencies` & `installPaths` in your box.json and then run `box install`, CommandBox will properly fetch it from ForgeBox however, due to how the package's box.json is set up, CommandBox picks up the key as `fw1` and will add those entries to the project's box.json. This doesn't break anything but does create room for future package conflicts and confusion.

After some discussion with Brad, apparently the use of 2 packages, one stable and one dev, along with different slugs in box.json is an older style that can be issue prone. CommandBox/ForgeBox makes heavier use of deciphering stable/dev releases through the [semver](https://commandbox.ortusbooks.com/content/packages/managing_version.html) patterns.

We could continue maintaining 2 packages but have separate box.json files to handle separate slugs. Doable, but not standard anymore. I don't suggest this option.

## So here's what I suggest...

Have one package on ForgeBox for all releases. The versioning will be handled by updating box.json info per release and telling each recorded version where to get that release.

**More details...**

On ForgeBox, you can manually specify `stable` vs `bleeding edge` releases when creating a version of a package. When publishing with CommandBox, ForgeBox is intuitive to decide these version types based on semver. (ie: `fw1-4.1.0` is a stable release and `fw1-4.5.0-SNAPSHOT` is bleeding edge)

In the same scenario, manually creating a version requires box.json info and publishing from CommandBox will use the box.json from the package being authored. This is where you can safely define the same `fw1` slug but make it unique with a version number and download location.

So in the event of stable releases, we can create a versioned release on ForgeBox that links to to a given zip file release on GitHub. For the dev/bleeding edge release, you can also create a version release in the same ForgeBox package and simply edit the version and location in that release's box.json to reflect any time a new development version is actively being worked on. RCs, Betas and such can be marked as stable or dev releases as needed.

If a user wants a stable release they can ask CommandBox for it like so...

- `box install fw1`
- `box install fw1@stable`
- `box install fw1@4.1.0`
etc...

If they want the development version they can call it like this...

- `box install fw1@be`
- `box install fw1@4.5.0-SNAPSHOT`
- `box install fw1@4.5.0-RC1`
etc...

**So what needs to change?**

Retire the `fw1-dev` ForgeBox package. Obviously it would be a good idea to leave it around for a "_deprecation_" period.

Create a new version release in the main `fw1` ForgeBox package, uncheck the stable option and specify the current semver status & where to grab that release. In this case pointing to the zip file for the develop branch will suffice. The version supplied will identify it as the bleeding edge version. RCs and Betas can be created as stable releases or just phase out as the develop branch is updated on ForgeBox.

I've literally been pouring over this way of handling ForgeBox/CommandBox packages for the first time today, but it seems pretty straight forward and will alleviate future confusion. Also lose the need to manage 2 packages!

I'm all for assisting in this transition so let me know of what help/clarification is needed and if there are any questions!

**Comment by seancorfield** [comment]
Yup, FW/1's use of ForgeBox predates the addition of version handling pretty much completely. I raised the issue several times with Brad and Luis and they kept saying "it's coming" -- and it came and FW/1 didn't change because "it worked" and I was only making about one release a year so figuring out how ForgeBox had changed wasn't high on my list, I'm afraid. I'm perfectly happy for you to do whatever's necessary to fix this and I'll do any tasks necessary with my account on ForgeBox (can a project on ForgeBox have multiple accounts associated to login and manage?).

**Comment by cfchef** [comment]
Ya, I recall the minimal efforts and features of versioning back when I committed the first box.json for the branch. Today is the day the old ways are working against me, and they will continue to as we're about to push out a big app heavily using CommandBox and FW/1.

I can draft up what the box.json info should look like for the develop version on ForgeBox and layout whatever we might need to keep in mind for future updates. It would appear we can leave the box files in the repos alone as they don't directly tie to package info on ForgeBox anymore.

I don't know if there is a multi-user concept on ForgeBox so I'll ping Brad in regards. If anything I'll pass on whatever needs to be pasted into the config section of ForgeBox.

Cheers, Sean.

**Comment by seancorfield** [comment]
I made a few changes, based on actually _reading_ the ForgeBox docs (shock, horror!) and *published* 4.5.0-SNAPSHOT using the normal machinery, i.e., `box publish`, and I can now do `box install fw1@be` and it works as expected. That was easier than I expected!

It looks like, going forward, as look as I use `box publish`, it'll all just "do the right thing"?

I'll update the `fw1-dev` to indicate it is deprecated and to use the bleeding edge version instead.

**Comment by seancorfield** [comment]
I guess my big remaining question is how/whether ForgeBox versions tie to GitHub versions? It looks like ForgeBox has sprouted better GitHub integration.

**Comment by seancorfield** [comment]
https://www.forgebox.io/view/fw1 is the main package and shows a SNAPSHOT now although `box install fw1@be` does *not* install it :( It seems to install the stable 4.1.0 version, not the develop branch, so I'm a bit confused now.

https://www.forgebox.io/view/fw1-dev is the deprecated version, so at least I think I got that part right.

**Comment by cfchef** [comment]
Cool! CommandBox has come a long way with its capabilities. It's really a delight for what I do in CFML these days. But ya, a `bump` of minor/major and then `publish` should "just work".

It would appear that the box.json in the actual repo is more for dependencies and general info to the project. Or if you install via the github endpoint. ForgeBox seems to store a individual "copy" of the box.json info you feed it from either manual or commandbox publishes. So you can define version at will and not effect the main repository if you just want to target a specific release.

As a side note, Brad informed me that multi-users for packages is in the works but in the meantime you could share the API key generated by commandbox when you connect to ForgeBox if you wanted an alternative to sharing publish rights.

Always happy to help with the box integration.

**Comment by cfchef** [comment]
Missed your last comment but I'll have a look real quick.

**Comment by cfchef** [comment]
@seancorfield I don't see a download option for the snapshot version on ForgeBox. I'd verify on ForgeBox that the box.json info is pointing to a source to download.

**Comment by seancorfield** [comment]
According to the docs on bleeding edge, that makes it clone/download the source (yes, watched it do it) but it seems to default to *master* branch. If ForgeBox doesn't know to treat snapshots as *develop* branch, I'm happy to switch how versions handled in FW/1 from now on -- and update the default branch (which is *develop* -- which is why I was surprised that box still gets the master version) and the contributing notes etc, etc.

If I'm using ForgeBox primarily going forward, the master/develop branch isn't as important, since Git tags will get added automatically anyway.

But it does seem like we need feedback from Brad here.

**Comment by cfchef** [comment]
Hmm. I figured that when you add a release version on ForgeBox, since it requires the box.json layout, if you pointed it to the develop zip as the location, then it should just work. It seemed like it was separate like that. I could certainly be wrong.

If you have a look at the box-products channel on Slack, Brad and I had a convo in regards earlier today. Maybe you can grab some insight from it. I'll have to re-look at what I reviewed today to maybe get a better grasp.

**Comment by seancorfield** [comment]
Looks like we're all good here now -- thank you so much for your help @cfchef ! Closing this out.

**Comment by cfchef** [comment]
👍🏻
