### ISSUE TITLE
Render null data

### ISSUE THREAD

**Issue by neoneo** [framework-one/fw1#484]
Following up on this topic: https://groups.google.com/forum/#!topic/framework-one/VuAZ_SpInP0

My use case: the api is a wrapper around the database, not much more. If a single object is requested (a query by id), it is my intention to return just this object, or null if the object does not exist in the database.

A straightforward workaround is to wrap it in an object such as `{"data":null}`, which is what I first did. But when I discovered that `null` (and `"some string"`, etc.) is actually valid JSON by itself I liked the elegance of omitting this wrapper.

The change I proposed: https://github.com/neoneo/fw1/commit/a6b7608cd00def59319d387daa635b7269a63ebd

I agree with your remark that the code is repetitive. A possible solution is a function like this:
```
private any function get(struct data, string key) {
    return structKeyExists(data, key) ? data[key] : javaCast("null", "");
}
```
And then use `get(requestData, "data")` or `get(arguments, "v")` instead.

In Lucee and CF11+ you can use `?:`, which is still repetitive but acceptable in my opinion, given the nature of null in CFML. This would be an option if CF10 is dropped at some point.

Still another solution would be to change nothing in the code, and enable null support on Lucee. Is null support officially supported in FW/1 and friends? (although Testbox would have to support it too, which it didn't a few years ago, I haven't checked since).

Any other suggestions?

**Comment by neoneo** [comment]
Mmm, come to think of it, an api would return 404 in this case...

Another example would be a relationship that is allowed to be empty. In that case it would be ok to return a 200 status with a null value.

**Comment by seancorfield** [comment]
If you're returning "No Content" and intending that to indicate success, you should really return 204 (and that's usually the successful result of a mutating operation that has no specific return value). 404 is fine for "Not Found" on a query.

Neither of those address the ability to still return JSON and an empty result. This definitely needs more analysis before deciding on a path.

**Comment by seancorfield** [comment]
I've no idea what the correct approach is here. There's a clear workaround (wrapping the null result) so maybe this is just a limitation people have to live with? I haven't seen any other requests for this, either prior or since. @sneiland

**Comment by sneiland** [comment]
On reflection my initial thought is that there is a difference between what is valid json (which can come from any source) and the responses from a rest api. In the situation outlined here going by REST design principles a URI of /path/to/object/{non_existing_id} should return a 404 since that entity does not exist.

An operation which performs a mutation without returning data should return a 204 response.

Neither of these two types of operation should return a null so by that reasoning I am going to close this.
