### ISSUE TITLE
invalid component definition, can't find component [framework.ioc]

### ISSUE THREAD

**Issue by dougmolineux** [framework-one/fw1#485]
Hi there,

I am trying to get an existing project setup, and I have setup Lucee successfully, for some reason I am seeing this error:
```
Exception in onError

The action main.default failed.

The key [SESSIONFACADE] does not exist, only the following keys are available: [action,INLINESCRIPT,SECTION,subsection,subsubsection].

Original exception in onApplicationStart

The action main.default failed.

invalid component definition, can't find component [framework.ioc]

(expression)
```
Any advice would be hugely helpful,

Thank you!

**Comment by seancorfield** [comment]
Not a bug in the framework. Please post to the mailing list with full details of your code / setup and someone will help you there.

**Comment by dougmolineux** [comment]
Oh thanks!

**Comment by dougmolineux** [comment]
any clues at all?>

**Comment by seancorfield** [comment]
You need to provide a lot more detail.

Structure of your project, mappings, your Application.cfc (as much as you can share).

If it can’t find framework.ioc, it sounds like your mappings are not set up correctly.

Sean Corfield -- (970) FOR-SEAN -- (904) 302-SEAN
An Architect's View -- http://corfield.org/

"If you're not annoying somebody, you're not really alive."
-- Margaret Atwood

From: Doug Molineux
Sent: Friday, August 18, 2017 10:00 AM
To: framework-one/fw1
Cc: Subscribed
Subject: [framework-one/fw1] invalid component definition, can't findcomponent [framework.ioc] (#485)

Hi there,
I am trying to get an existing project setup, and I have setup Lucee successfully, for some reason I am seeing this error:
Exception in onError

The action main.default failed.

The key [SESSIONFACADE] does not exist, only the following keys are available: [action,INLINESCRIPT,SECTION,subsection,subsubsection].

Original exception in onApplicationStart

The action main.default failed.

invalid component definition, can't find component [framework.ioc]

(expression)
Any advice would be hugely helpful,
Thank you!

**Comment by seancorfield** [comment]
GitHub issues are *not a support channel* -- post to the mailing list!!!

**Comment by dougmolineux** [comment]
i will try to avoid this framework at all costs

**Comment by mjclemente** [comment]
@dougmolineux That's a bit abrupt. There's a strong, responsive support community willing to help you get started. Sean, in particular, goes out of his way to help people. This just isn't the place to ask questions. The mailing list is here: https://groups.google.com/forum/#!forum/framework-one

I'd also recommend trying the #fw1 channel on the CFML Slack channel: http://cfml-slack.herokuapp.com/

If you decide to move on, best of luck with your project.
