### ISSUE TITLE
When using singletonPattern on ioc.cfc injection by property breaks

### ISSUE THREAD

**Issue by Yamaha32088** [framework-one/fw1#487]
I may have found a bug when you use the `singletonPattern` configuration parameter the injection by component property breaks. When dumping the component returned the property is null but after removing the configuration parameter `singletonPattern` it starts to work as expected.

Here is my code:

Inside Application.cfc: 

```
function onApplicationStart() {
    APPLICATION.beanFactory = new system.di1.ioc( folders=["models"], config={ singletonPattern = "(Service|Factory)$" });
    return true;
}
```

EmailsBean.cfc:
```
component accessors="true" {
	
	property name="ReceiveEmailsBean" type="any";

	public any function boom() {
		
	}

}
```

ReceiveEmailsBean.cfc:

```
component accessors="true" {
	
	public any function blah() {

	}

}
```

How I am calling it:

```
var blah = application.beanFactory.getBean('EmailsBean');
dump(blah)
```

**Comment by jcberquist** [comment]
@Yamaha32088 I think this is what is happening: since neither of your two components match the `singletonPattern` setting, they are identified by DI/1 as transients when it is in place. Transients are never injected by DI/1 via setters. You can see the note in the docs under  [Basic DI/1 Conventions](http://framework-one.github.io/documentation/4.1/using-di-one.html#basic-di1-conventions):
> Note that DI/1 will inject both singletons and transients via constructors, but it will inject only singletons via setters or properties, not transients.

**Comment by seancorfield** [comment]
@jcberquist is correct: DI/1 will only inject a transient (in your case `ReceiveEmailsBean`) via the _constructor_, not via the setter or property. Per the documentation: http://framework-one.github.io/documentation/4.1/using-di-one.html#basic-di1-conventions -- here's the relevant paragraph in full:
> Note that DI/1 will inject both singletons and transients via constructors, but it will inject only singletons via setters or properties, not transients. Injecting transients in those situations often leads to unexpected results (consider a transient invoice bean that has a setCustomer() method when you also have a transient customer bean - you almost certainly don’t want DI/1 to automatically create a customer instance and inject it every time you ask DI/1 for a new invoice bean!). If a constructor argument matches a transient bean, DI/1 will still create an instance since it has to finish constructing the original bean.

**Comment by Yamaha32088** [comment]
You guys are right, I missed that part of the documentation. Thanks for the help
