### ISSUE TITLE
Controllers in subsystems not found by DI/1 when diLocations includes the base prefix

### ISSUE THREAD

**Issue by cfvonner** [framework-one/fw1#497]
This issue pops up when an application's code is placed outside the web root (such as in `../app`).  To accommodate that, one must include
`base : '/app',
diLocations : [ "/app/model", "/app/controllers" ]`
in the FW/1 configuration.  Since `diLocations` is being explicitly set, DI/1 isn't able to automatically crawl the subsystems to wire up the model and controller cfcs.

The workaround is to modify the `diLocations` like so:
`diLocations : [ "/app/model", "/app/controllers", "model", "controllers" ]`.

**Comment by seancorfield** [comment]
Some more background: in order for "conventions" to work in subsystems in "most cases", FW/1 makes some fairly conservative assumptions about paths and how to map the original `diLocations` to how they should work inside subsystems.

One of the big assumptions is that the default `diLocations` (`model`, `controllers`) is going to "look like" what most people specify -- and this is blatantly untrue when you specify `base` (which, ironically, the subsystems code _does_ include).

I'm not yet sure what the right approach is but I suspect detecting whether `base` is a prefix of the locations in `diLocations` might be a good first step...

**Comment by cfvonner** [comment]
FW/1 config settings allow specifying a `base : '/somepathoutsidewebroot'`.  I'm assuming FW/1 automatically starts scanning for cfcs in folders named "model" and "controllers" **in the web root**.  What if a DI/1 config variable called `base` was added, with the default setting being `/` (or web root)?  DI/1 would then use `base` as the starting point for scanning for cfcs.  Then if an alternate diconfig `base` was set, it would just look there instead.  At that point `diLocations` would only be needed to be set if you had non-standard folder names, such as "handlers".

**Comment by seancorfield** [comment]
This isn't about DI/1 config -- it's FW/1 setting things up for DI/1 for subsystems.

**Comment by cfvonner** [comment]
Could this issue be resolved if `cfcbase` was set in the FW/1 config?  It seems like it's being used to define paths for controllers in `getCachedController()` starting here: https://github.com/framework-one/fw1/blob/8f0681fe36aabcd3617cee5b0201f08e49a1756b/framework/one.cfc#L1837

Although from https://github.com/framework-one/fw1/blob/8f0681fe36aabcd3617cee5b0201f08e49a1756b/framework/one.cfc#L2528 it appears that `cfcbase` is automatically created from `base`, the leading slash is removed, and all other slashes are converted to dots.  So in theory, I shouldn't even have to set `diLocations` and FW/1 should be able to find my controllers/model based on the setting of  `base`.

Am I understanding things correctly?

**Comment by seancorfield** [comment]
No, `cfcbase` is a legacy setting that predates (and is separate from) using DI/1 to manage controllers.

**Comment by cfvonner** [comment]
If I recall correctly, when I first started this project using the alternate application structure, FW/1 couldn't find the controllers/model (even though `base` was set to `/app`) unless I specified the `diLocations` explicitly (e.g. `/app/controllers`, and `/app/model`.  This was back on FW/1 version 3.5.  Was anything changed in subsequent versions that might have removed the need to set `diLocations` for alternate application structure situations?

**Comment by seancorfield** [comment]
I'm not sure where we stand with this one? Do we have a small, self-contained repro test case? Is this really a bug or just a misconfiguration that needs better documentation? @sneiland

**Comment by sneiland** [comment]
@cfvonner Unless you can supply a self-contained repro test case I'm going to mark this as a misconfiguration and closed.

**Comment by cfvonner** [comment]
That's fine. Everything is currently working with adding the paths I need to `base` and `diLocations`.
