### ISSUE TITLE
Modify request level handling via subsystem configuration.

### ISSUE THREAD

**Issue by mjclemente** [framework-one/fw1#498]
I think it might be helpful to have the ability to modify request level handling via subsystem configuration, i.e. 
```cfc
  subsystems = {
      "api" = {
        decodeRequestBody = true
      }
    }
```
This idea emerged, as shown in the code snippet, from the desire to enable `decodeRequestBody` for a particular subsystem, but not for the main application. Right now this isn't possible via the framework, though there are workarounds.

Not sure if others would also find this helpful, or if it would have utility beyond the request body being decoded.

**Comment by seancorfield** [comment]
Worth investigating but I've no idea how much work it would be @sneiland

**Comment by sneiland** [comment]
This looks like a useful feature, but it doesn't seem straightforward to implement with subsystems the way they are currently structured. For now I'm going to keep this open as a feature request for the next major release.
