### ISSUE TITLE
decodeRequestBody fails for JSON arrays

### ISSUE THREAD

**Issue by mjclemente** [framework-one/fw1#503]
While I don't understand their reasoning, some webhook providers wrap their JSON posts in array notation. For example, here's a stripped down webhook from the transactional email provider Sparkpost
```json
[
  {
    "msys": {
      "relay_message": {
        "rcpt_to": "xxxxxx@xxxxxx.xxxxxx.com",
        "friendly_from": "xxxxxx@gmail.com",
        "content": {
          "text": "Just the message?",
          "subject": "Really sparkpost"
        },
        "protocol": "smtp"
      }
    }
  }
]
```
From what I could tell, having an array as the top level JSON text is valid; from the JSON Grammar portion of the [RFC](https://tools.ietf.org/html/rfc4627):
> A JSON text is a serialized object or array.

When this type of JSON data is sent to a FW/1 app, it errors, as `structAppend()` is used to add the data to the request context: `structAppend( request.context, bodyStruct );`.

I'm happy to put together a PR to account for arrays (if you'd want it); I'd imagine it would only be a line or two, checking if the deserialized data was an array.

Thanks!

**Comment by seancorfield** [comment]
Interesting. I think I'd lean toward just calling it `body`, so the `structAppend()` line would be replaced by:
```
if ( isStruct( bodyStruct ) ) {
    structAppend( request.context, bodyStruct );
} else {
    request.context.body = bodyStruct;
}
```
Would that suffice?

**Comment by mjclemente** [comment]
Works for me! 👍
