### ISSUE TITLE
Help Migrating from 2.5 to 4.2

### ISSUE THREAD

**Issue by rmilejcz** [framework-one/fw1#506]
I've been working on updating an old coldbase to use modern fw/1. So far it's been okay but I'm running into an issue overwriting fw/1 methods and I did not write any of this code so making sense of it is proving to be taxing.

I've opted to maintain the old Application structure, please excuse the poor formatting

    component extends="framework.one" {
      /* lots of variables initialized here */

 	variables.framework = {
		reloadApplicationOnEveryRequest = true,
		home="admin:dashboard.index",
		unhandledPaths="/scripts,/test,/api",
		base="/app",
		usingSubsystems=false,
		defaultSubsystem="public",
		siteWideLayoutSubsystem="common",
		diLocations = "/app/model",
		subsystemDelimiter = ':',
		applicationKey = 'kalosflorida',
		diConfig = {
			singletonPattern="(Service|DAO|Helper)$",
			loadListener = factoryConfig
		}
	}

	function factoryConfig( bf ) {
		//add datamgr to the mix
		bf.addBean("Datamgr", new lib.datamgr.DataMgr());
		
		if(findNoCase("new.kalosflorida.com", cgi.SERVER_NAME) or findNoCase("app.kalosflorida.com", cgi.SERVER_NAME)) {
			var environment = 'production';
		} else {
			var environment = 'development';
		}
		//add error handling bean
		if(environment == "development"){
			var projectId = "206fadba-84e2-11e5-98e9-c8e0eb140473";
		} else {
			var projectId = "206fadba-fsdfa-52fs-98e9-c8e0eb140473";
		}
		bf.addBean("Watchman", new lib.watchman.Watchman("0A043084731b4479a2a8557128d39B97256738b6", "2313644a1e874cF49b6d18Be6899791EfA26e605ED214E67B0","http://watchman.kalosflorida.com/api/error", projectId));

		//add recaptcha to the mix
		bf.addBean("Recaptcha", new lib.recaptcha.Recaptcha(true));

		//add custom_functions to the mix 
		bf.addBean("custom_functions", new lib.custom_functions.custom_functions(true));
		
		bf.addBean("genericDao", new lib.com.database.dao());
	}

	public function setupRequest(){
	  if (getEnvironment() == "development") {
	    variables.framework.reloadApplicationOnEveryRequest = true;
	  	application.s3.internalDocBucket = "kalos-internal-documents-dev";
	  	application.s3.docs = "kalosdocs-prod";
	  } else {
	    application.s3.internalDocBucket = "kalos-internal-documents";
	    application.s3.docs = "kalosdocs-prod";
	  }
     	//writedump(session);writedump(cookie);
    if(
			!isdefined('session.user.id')
			AND 
			isdefined('cookie.user_id')
			AND
			len(cookie.user_id) GT 0
		) {
	    controller("security.cookiemanage");
    }
    request.currentEnvironment = variables.getEnvironment();
		request.context.startTime = getTickCount();
		if(isDefined("url.ormReload")){
			ormReload();
		}
		if(isDefined("url.reloadApp")){
			///factoryConfig();
			setupSession();
		}
		if(findnocase('dl2.cfm',cgi.script_name)){
			flashInsert(error="Sorry, this link no longer works. Please either log in to view the document or contact Kalos Staff to resend");		
		}
		controller("security.check");
	}

    function setupSession() {
        session.user.LoggedIn = false;
        session.user.IsAdmin = false;
        session.user.isRequestOffAdmin = false;
        session.user.IsSU = false;
        session.user.IsEmployee = false;
        session.user.id = '';
        session.message = '';
        
        session.user.access_servicecall_screen             = false;
        session.user.access_service_entryItem_screen       = false;
        session.user.access_modified_dashboard             = false;

        session.user.access_flat_rate_sheet                = false;

        session.user.access_spiff_tool_fund				   = false;
        session.user.spiff_tool_admin					   = false;
        session.user.service_manager_admin				   = false;
        
        session.aesKey = generateSecretKey("AES");
	}
    }
    

My issue here is that instead of calling `setupRequest` when requests are called, I am getting dumped to my index page which requires authentication and so an error is thrown.

I would expect the call to `controller("security.check");` to then call that function in my security controller, which would redirect me to the login page, but this does not happen.

I've been searching for HOURS, combing through your documentation and I cannot solve this for the life of me. Any help is greatly appreciated

**Comment by dnando** [comment]
You wrote that you think you are "running into an issue overwriting fw/1
methods". You also write that you're migrating the codebase to fw/1 4.2.
Maybe you could elaborate a bit more on these points. Which fw/1 methods
are you overwriting? And why?

**Comment by aliaspooryorik** [comment]
This isn't an issue with the framework. If you need help, then can I suggest you join the FW1 channel on Slack. https://cfml-slack.herokuapp.com/

**Comment by rmilejcz** [comment]
>You wrote that you think you are "running into an issue overwriting fw/1
methods". You also write that you're migrating the codebase to fw/1 4.2.
Maybe you could elaborate a bit more on these points. Which fw/1 methods
are you overwriting? And why?

It's in my post already, I'm overwriting setupRequest to add a call to `controller('security.check')`, which is exactly how the authentication dictates

>This isn't an issue with the framework.

If you're so certain of this then can you explain to me what I'm doing incorrectly?

**Comment by aliaspooryorik** [comment]
I think the confusion is that calling `controller` in `setupRequest` adds that controller method to the queue. It is not executed immediately. You can enable `variables.framework.trace` to see how FW/1 queues and executes controllers / views / layouts etc.

Can you create a simple stand alone example of the issue that you think you have in FW/1 without all your extra application specific code in?

**Comment by Richardtugwell** [comment]
I think John is right - normally I have an authentication service that I
call in setupRequest() and just redirect or something... of course I don't
know what your controller method is doing

Richard Tugwell

https://instagram.com/richard_tugwell
