### ISSUE TITLE
framework.redirect( preserve: all ) doesn't preserve anything on Lucee

### ISSUE THREAD

**Issue by atuttle** [framework-one/fw1#517]
In my testing it seems like the `preserve: "all"` option for the `framework.redirect()` method doesn't preserve anything.

```
component accessors = true {

    property framework;

    function a(rc){
        rc.x = 1;
        rc.y = 2;
        rc.z = 3;

        return framework.redirect( action: 'test.b', preserve: 'all' );
    }

    function b(rc){
        writeDump(rc);abort;
    }

}
```

Given the above controller, if you navigated to the A action, you would expect it to redirect to B and re-hydrate RC with the values for x, y, and z; but it seems not to.

I'm using the latest FW/1 v4.2 and Lucee 5.3.3+62.

Not sure if this matters but we're not using the provided session scope, we're using Redis for sessions, provided through [Sidecar](https://github.com/MotorsportReg/sidecar), and I've overridden the FW/1 session facade functions (sessionRead, sessionWrite, etc) to make FW/1 use the same Redis session storage.

**Comment by sneiland** [comment]
Unable to reproduce on Lucee 5.3.3.062 running fw/1 4.2.0 on ubuntu vagrant box.

@atuttle I suspect the issue is related to redis/sidecar.
