### ISSUE TITLE
FW1 & MURA CMS 6.2.6303 & Coldfusion 2018

### ISSUE THREAD

**Issue by charlesr1971** [framework-one/fw1#520]
MURA CMS 6.2.6303
Windows 10
Coldfusion 2018

I have just upgraded my CF application server from CF11 to CF2018. The front end works fine, but when I try and login to /admin, I get a CF error 500:

```
Could not find the ColdFusion component or interface blog1.establishmindfulness.admin.framework.
Ensure that the name is correct and that the component or interface exists.
```

This exception is thrown on all of my MURA CMS 6 websites. I have tried reloading the application, clearing the browser cache, restarting the application server, and nothing works. I have even tried creating a new MURA CMS website, using a new download, but I cannot access the admin page. 

I had already made 2 fixes to get CF2018 to work with the front end. I had to remove the timeout attribute from the cfschedule tag in **config/appcfc/onApplicationStart_include.cfm**  and also I added a fix in **requirements/MURA/bean/ioc.cfc**, but I think there is a more serious issue with the FW1 subsystem!

And, everything works fine in the latest version of Lucee 5.3.6

Any help would be most appreciated.

**Comment by charlesr1971** [comment]
I raised a bug report, a while ago, on Blue River’s MURA CMS repo, but I have had no reply yet?

**Comment by sneiland** [comment]
This is a server issue as opposed to a fw/1 issue. I've seen it come up with other non fw1 codebases that have migrated to cf2018 as well. I dont remember what the fix was but I believe it involved rebuilding some part of the connectors.
