### ISSUE TITLE
PreserveKey is not passed when using fw.redirect with Lucee Modern local scope mode

### ISSUE THREAD

**Issue by rodionbykov** [framework-one/fw1#522]
In function getNextPreserveKeyAndPurgeOld() variables nextPreserveKey and oldKeyToPurge will not be set if Lucee has 'Local Scope Mode' set to 'Modern'. In this case variables will be created inside closure Local scope, instead of caller function Local scope. This causes &fw1pk not be passed in URL and 'preserved' variables lost.

**Comment by sebgmc** [comment]
I've had similar issues - it baffled me for a long time and ended up working around it.
FW/1 4.2
Lucee 4.5.x
Windows

**Comment by tonyjunkes** [comment]
I believe I have a working fix for this. At least with initial testing. Just need to do a little more scenario testing and make sure all supported engines are still happy. Probably have a PR ready by the weekend.

**Comment by atuttle** [comment]
It looks like this was fixed by #526 so this issue should be closed. Am I right?

**Comment by DaveAndersonxx** [comment]
I ran into this problem on Lucee 5.4.4.38 and fw/1 4.3. The Lucee setting for modern local scope handling didn't seem to have any impact on it.  I resolved it by modifying the doController() method and adding a call to restoreFlashContext() right before the controller method is invoked.
