### ISSUE TITLE
fw1 4.2 (Can not display foreign characters in views)

### ISSUE THREAD

**Issue by asimakos** [framework-one/fw1#530]
I have got the following main Controller default action in fw/1 (framework one 4.2), where i define some rc scope variables to be displayed in views/main/default.cfm. 

main.cfc

```
 function default( struct rc ) {

        rc.name="ΡΨΩΓΔ";
        rc.dupl_name="üößä";
    } 
```
views/main/default.cfm

```
 <cfoutput>
    <p> #rc.name# </p>
    <p> #rc.dupl_name# </p>
   </cfoutput>
```

and finally in layouts/default.cfm

```
<cfoutput><!DOCTYPE html>
    <html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>
            A Simple FW/1 Layout Template
        </title>
    </head>
    <body>
       #body# 
    </body>
    </html>
</cfoutput>
```
Unfortunately i receive the following output 

Î¡Î¨Î©Î“Î”

Ã¼Ã¶ÃŸÃ¤

Any idea that could help me as i have used UTF-8 encoding? 

Regards

**Comment by sneiland** [comment]
This has nothing to do with the framework

**Comment by asimakos** [comment]
Yes indeed I just fixed it. I have to change lucee administration charset settings all to utf-8.

Regards
